### ISSUE TITLE
Tooltips for all parts of the report table

### ISSUE THREAD

**Issue by tomryder9** [rstudio/pointblank#104]
I really think this package is awesome and I'm using it constantly. It's the only R package that makes data checking both easy and really rigorous. I have to check a lot of datasets and find out what problems they have and this package seriously has all the tools for the job. Thanks for all the great work you're putting into it!!!

A feature request I'd like to make here is to have tooltips put on all of the different cells of the report table. If there there are a lot of values in a cell, the report only shows the first part of it and then ... . But a tooltip could provide a bit more info (could still be a high level summary).

Thank you  again. This is one of the best R packages around and it's still always getting better!

**Comment by rich-iannone** [comment]
I completely agree that this should be done for the report. Thank you for using the package!

**Comment by rich-iannone** [comment]
Currently working on implementing much better tooltips through integration of **balloon.css**. This is on top of ensuring that more table cells have tooltips at all, and, that the tooltips get better formatting. 

The small version of the agent report (mostly used for emails) will get standard HTML tooltips. I might consider making this an option and setting the defaults accordingly.
