### ISSUE TITLE
New CRAN release?

### ISSUE THREAD

**Issue by rachelupton** [rstudio/pointblank#113]
This package is wonderful, I can't say that enough. However I'm wondering if there is a new CRAN release in the works? There are some excellent features that are currently only in the GitHub version and it would be good to have them available for all in an official CRAN release.

Thank you for working on this really awesome package!!! Super happy with all it's been able to help me with .

**Comment by rich-iannone** [comment]
There should definitely be a new release to CRAN, I totally agree with that.

@pachamaltese Would you be able to move the {dittodb} related tests to a new branch? We can definitely move it all back to master when {dittodb} is in CRAN.

**Comment by pachadotdev** [comment]
sure!

**Comment by pachadotdev** [comment]
@rich-iannone moved here https://github.com/rich-iannone/pointblank/pull/117

**Comment by rich-iannone** [comment]
@rachelupton The pointblank package (v0.4) is now available in CRAN. Thank you so much for your support and enthusiasm for the package!
