### ISSUE TITLE
Error in UseMethod("rename_") possible issues from dplyr 1.0?

### ISSUE THREAD

**Issue by daranzolin** [rstudio/pointblank#122]
I'm trying to do a rowwise validation and have been fighting an unusual error. Reprex below:

``` r
library(pointblank)

tbl <- dplyr::tibble(
  var1 = c("J", "J", "J", "J", "J"),
  var2 = c("R", "R", "R", "F", "N")
)

tbl %>% 
  expect_conjointly(
    ~ col_vals_not_equal(., vars(var1), "J"),
    ~ col_vals_not_in_set(., vars(var2), c("F", "N"))
  )
```

    #> Warning: `rename_()` is deprecated as of dplyr 0.7.0.
    #> Please use `rename()` instead.
    #> This warning is displayed once every 8 hours.
    #> Call `lifecycle::last_warnings()` to see where this warning was generated.

    #> Error in UseMethod("rename_"): no applicable method for 'rename_' applied to an object of class "NULL"

<sup>Created on 2020-06-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rich-iannone** [comment]
Sorry about this, thought I did all the dplyr 1.0.0 updating but missed this. This’ll be the next thing to get fixed.

**Comment by rich-iannone** [comment]
@daranzolin This is fixed now, sorry for the delay in getting to it. Please let me know if there is any other odd behavior in the package functions, especially with `conjointly()`. And, also let me know if there are any useful feature requests for that function (or others)!

**Comment by Gil-Luna** [comment]
I have the same error using this loop, Could somebody help me? :) Thanks!
start_dates <- seq(as.Date('2015-01-01'), as.Date('2020-12-01'), 'months')

meteocat_2015_Roses <-
  purrr::map_dfr(
    .x = start_dates,
    .f = function(start_date) {
      res <- get_meteo_from(
        'meteocat',
        meteocat_options(
          api_key = keyring::key_get('meteocat'),
          resolution = 'daily',
          start_date = start_date ,
          stations = ('D4')
        )
      )
      return(res)
    }
  )


Here the hide traceback:

 Error in UseMethod("rename") : 
  no applicable method for 'rename' applied to an object of class "NULL" 
12.
dplyr::rename(., station_province = .data$nom) 
11.
response_content[["provincia"]]["nom"] %>% dplyr::rename(station_province = .data$nom) 
10.
.get_info_meteocat(api_options) 
9.
api_function(options) 
8.
(function (service = c("aemet", "meteocat", "meteoclimatic", 
    "meteogalicia", "ria"), options) 
{
    service <- rlang::arg_match(service) ... 
7.
eval(mc, parent.frame()) 
6.
eval(mc, parent.frame()) 
5.
withVisible(eval(mc, parent.frame())) 
4.
get_meteo_from("meteocat", meteocat_options(api_key = keyring::key_get("meteocat"), 
    resolution = "daily", start_date = start_date, stations = ("D4"))) 
3.
.f(.x[[i]], ...) 
2.
map(.x, .f, ...) 
1.
purrr::map_dfr(.x = start_dates, .f = function(start_date) {
    res <- get_meteo_from("meteocat", meteocat_options(api_key = keyring::key_get("meteocat"), 
        resolution = "daily", start_date = start_date, stations = ("D4")))
    return(res) ...

**Comment by CarlesCayuela** [comment]
Hi @Gil-Luna,

I am facing the same problem. Did you solve it? Thank you!

Carles
