### ISSUE TITLE
Writing validation results to a file

### ISSUE THREAD

**Issue by tomryder9** [rstudio/pointblank#123]
I'd like to have the validation results stored as a file. This way we can recall a past data quality validation run and compare with a recent run. Is this something that you're already thinking about doing? 

Thanks!

**Comment by rich-iannone** [comment]
Yes, this is in the works. It'll involve storing all previous runs and this will be part of a larger system (i.e., with a configuration file and script per data source).

**Comment by rich-iannone** [comment]
This was done in #130. Closing now.
