### ISSUE TITLE
"Composite" validation functions ?

### ISSUE THREAD

**Issue by kylelundstedt** [rstudio/pointblank#127]
Hi @rich-iannone 

I've got a conceptual question about whether and how to "compose" validation functions in order to simplify an industry-specific data quality or data pipeline analysis.

Let's use a consumer finance industry example - making loans to borrowers.  Assume I have a bunch of "loan"-related tables in my remote database that track variables such as original_loan_amount, the current_loan_amount, the original_interest_rate, the current_interest_rate, the original_payment, the current_payment, and a number of other related variables.  I'd like to take the "core" validation functions from `pointblank`, such as `col_vals_between` and `col_vals_not_null`, and create "composite" validation functions specific to my finance industry use case.  

For example, given the "loan"-related tables described above, there will be a large number of variables across my tables that contain variations of "payment" (i.e.,  "original_payment", "current_payment", etc).  Therefore, I'd like to build a "composite" validation function called `col_vals_payment` that I can apply to all "payment"-related columns in the data, which would include a number of "core" validation functions tailored to my finance industry use case:

- `col_vals_between` $0 and $1,000; (our loans never have payments over $1000/mo)
- `col_vals_lte` the value of the "current_balance"; (you can't pay more than you owe)
-  `col_vals_equals` 0 when "current_balance" equals 0; (no need to make payments once loan is paid off)
- etc, etc

From your viewpoint as the package designer, does it make sense to construct these kind of "composite" validation functions?  If so, do you have a recommended method for building such functions?

Thanks for the advice!
Kyle

**Comment by rich-iannone** [comment]
If this is a persistent pattern in a lot of tables it might be worth it. Here is an example where I try to follow your validation rules:

```r

library(tidyverse)
library(pointblank)

payment_table <- 
  small_table %>%
  select(date, a, c, d) %>%
  mutate(first_payment = a * 150) %>%
  mutate(payment_two = c * 112) %>%
  mutate(current_balance = d * 2.16427) %>%
  mutate(current_balance = ifelse(current_balance < 500, 0, current_balance))


cols_vals_payment <- function(tbl,
                              match_for_payments = "payment",
                              all_between = c(0, 1000),
                              na_pass = FALSE,
                              threshold = 1) {
  
  payments_cols <- tbl %>% select(matches(match_for_payments)) %>% colnames()
  
  create_agent(tbl = tbl, actions = action_levels(stop_at = threshold)) %>%
    col_vals_between(
      columns = payments_cols,
      left = all_between[1], right = all_between[2],
      na_pass = na_pass
    ) %>%
    col_vals_lte(
      columns = payments_cols,
      value = "current_balance",
      na_pass = na_pass
    ) %>%
    col_vals_equal(
      columns = payments_cols,
      value = 0,
      preconditions = ~ . %>% dplyr::filter_at(vars(matches("current_balance")), ~ .x ==  0),
      na_pass = na_pass
    ) %>%
    interrogate()
}

cols_vals_payment(tbl = payment_table)
```

Here is the output:

<img width="1020" alt="composite-validation-report" src="https://user-images.githubusercontent.com/5612024/89853863-738a2c80-db60-11ea-9d94-6b8564c6973a.png">

It's not too bad except that I had to hardcode the `current_balance` column into the function. This is because currently the `{{ }}` doesn't work inside `preconditions`. So, it can be done but ultimately up to you as to whether the time taken to write/test a function like this saves future work.

**Comment by kylelundstedt** [comment]
Wow!  This is REALLY cool, @rich-iannone !!!  Thanks so much.
