### ISSUE TITLE
Validation of table dimensions

### ISSUE THREAD

**Issue by stevewynnegh** [rstudio/pointblank#128]
Thanks for making this really useful package! It’s an incredible achievement and solves a lot of problems in the data quality space. 

I have a feature request, with some implementation ideas. Sometimes it’s useful to validate the dimensions of a table (e.g. I should have at least x rows, there should be y columns). I thought maybe there should be a separate validation function for this, but maybe there should be a precondition function that creates a one-row summary table (With headings 'columns’ and ‘rows’). Then, any of the Validation Functions that do comparisons can be used.

**Comment by rich-iannone** [comment]
A function that can be used in `preconditions` would be best for this, I totally agree. This function needs to be tested to ensure that the table dimensions table is produced accurately for all database types that we support. Fortunately, that very thing has been manually tested across all supported data sources (i.e., there already is a code path for getting column and row counts).

**Comment by rich-iannone** [comment]
Sorry for taking so long to get to this but this is now possible in *lots* of different ways. 

For checking of exact dimensions we can use `col_count_match()` and `row_count_match()`. We can use the `tt_tbl_dims()` table transformer in `preconditions` to mutate the target table and perform any sort of comparison check (examples: https://rich-iannone.github.io/pointblank/reference/tt_tbl_dims.html). Finally, we can use the `specially()` function and provide an anonymous function like `function(x) ncol(x) >= 2` to perform the check!
