### ISSUE TITLE
col_values_in_set passes even when values are not in the set

### ISSUE THREAD

**Issue by ekothe** [rstudio/pointblank#13]
The `col_values_in_set ` test appears to pass regardless of whether or not values are actually in the set. See reproducible example below:

Create a simple two column data frame

```
df <-
  data.frame(
    a = c(1, 2, 3, 4),
    b = c("one", "two", "three", "four"),
    stringsAsFactors = FALSE)
```

Validate that all numerical values in column `a` belong to a numerical set, and, that all values in column `b` belong to a set of string values. Note that _none_ of the values in _either_ validation set should pass.

```
agent <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
  col_vals_in_set(
    column = a,
    set = 10:20) %>%
  col_vals_in_set(
    column = b,
    set = c("mouse", "dog", "cat", "pig")) %>%
  interrogate()
```

However, all validation checks are reported as passed
```
all_passed(agent)
[1] TRUE
```

**Comment by rich-iannone** [comment]
@ekothe Thanks for looking into this. I created a fix, corrected the affected tests, and tests pass now. This is what I changed:

```
      if (agent$validation_set$assertion_type[i] == "col_vals_in_set") {
        
        # Use the column name as an `rlang` symbol
        column <- rlang::sym(agent$validation_set$column[i])
        
        # Get the final judgment on the table and the query
        judgment <-
          table %>%
          dplyr::mutate(pb_is_good_ = case_when(
            rlang::UQ(column) %in% set ~ TRUE,
            !(rlang::UQ(column) %in% set) ~ FALSE
          ))
      }
      
      if (agent$validation_set$assertion_type[i] == "col_vals_not_in_set") {
        
        # Use the column name as an `rlang` symbol
        column <- rlang::sym(agent$validation_set$column[i])
        
        # Get the final judgment on the table and the query
        judgment <-
          table %>%
          dplyr::mutate(pb_is_good_ = case_when(
            !(rlang::UQ(column) %in% set) ~ TRUE,
            rlang::UQ(column) %in% set ~ FALSE
          ))
      }
```

The code was written before **rlang** was available so there are still lots of **dplyr** function variants with underscores (e.g., `mutate_()`, `filter_()`).

I'm not entirely sure this will work on database tables. I remember `case_when()` not working very well, so, I'll need to test this later. If it doesn't work, it'll be possible to write separate, working statements for that context.
