### ISSUE TITLE
Identify the type of table being validated in the agent report (tibble, database)

### ISSUE THREAD

**Issue by shawnoneill-code** [rstudio/pointblank#132]
Hey Rich, this is a **very** useful package. Data quality is a big concern for our group and so this package is now central to our analytics processes. I really cannot thank you enough for the excellent work you put into this package!

My request is for the table report (agent report). Would it be possible to add a label at the top that describes the type of table being checked? Possible labels are `data.frame`, `tibble`, `MySQL` etc. Sometimes for us, the tables have both a local variant and a DB version and this would help us to make it more clear where the table came from.

**Comment by rich-iannone** [comment]
This is something that would be easy to implement, and, would add a ton of value. The plan is to overhaul the agent report and this could be a part of that work. Thanks for the great suggestion here!

**Comment by rich-iannone** [comment]
This is now added in a4edbcd36a21761412248b9df7a8e1adba30b70c. When doing a table validation with an agent like so:

```r
library(pointblank)

al <- action_levels(warn_at = 0.1, stop_at = 0.2)

agent <-
  small_table %>%
  create_agent(name = "local_table", actions = al) %>%
  col_vals_gt(vars(date_time), vars(date), na_pass = TRUE) %>%
  col_vals_gt(vars(b), vars(g), na_pass = TRUE) %>%
  col_vals_regex(vars(b), "[1-9]-[a-z]{3}-[0-9]{3}") %>%
  rows_distinct() %>%
  col_vals_gt(vars(d), 100) %>%
  col_vals_equal(vars(d), vars(d), na_pass = TRUE) %>%
  col_vals_between(vars(c), left = vars(a), right = vars(d), na_pass = TRUE) %>%
  col_vals_not_between(vars(c), left = 10, right = 20, na_pass = TRUE) %>%
  rows_distinct(vars(d, e, f)) %>%
  col_is_integer(vars(a)) %>%
  interrogate()

agent
```

The agent report now appears like this:

<img width="1262" alt="agent-report-table-type-time" src="https://user-images.githubusercontent.com/5612024/91629798-fea95600-e999-11ea-8e13-34d5e20dffc9.png">

I was also able to add the execution start time. Later on, I'll add support for the duration of the interrogation and the ending time.
