### ISSUE TITLE
get_sundered_data() fails when run on agent with one test

### ISSUE THREAD

**Issue by nickv9** [rstudio/pointblank#145]
Running `get_sundered_data()` on an agent with only one test returns an out of bounds error.

``` r
library(tidyverse)
library(pointblank)

agent <-
  create_agent(tbl = small_table) %>%
  col_vals_between(
    vars(c), left = vars(a), right = vars(d),
    na_pass = TRUE
  ) %>%
  interrogate()

agent %>% 
  get_sundered_data()
```

    #> Error in tbl_check_obj[[i + 1]]: subscript out of bounds

``` r
devtools::session_info()
```

    #> - Session info ---------------------------------------------------------------
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       Windows 10 x64              
    #>  system   x86_64, mingw32             
    #>  ui       RTerm                       
    #>  language (EN)                        
    #>  collate  English_United States.1252  
    #>  ctype    English_United States.1252  
    #>  tz       America/New_York            
    #>  date     2020-08-17                  
    #> 
    #> - Packages -------------------------------------------------------------------
    #>  package     * version    date       lib source        
    #>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.2)
    #>  backports     1.1.8      2020-06-17 [1] CRAN (R 4.0.2)
    #>  blastula      0.3.2      2020-05-19 [1] CRAN (R 4.0.2)
    #>  blob          1.2.1      2020-01-20 [1] CRAN (R 4.0.2)
    #>  broom         0.7.0      2020-07-09 [1] CRAN (R 4.0.2)
    #>  callr         3.4.3      2020-03-28 [1] CRAN (R 4.0.2)
    #>  cellranger    1.1.0      2016-07-27 [1] CRAN (R 4.0.2)
    #>  cli           2.0.2      2020-02-28 [1] CRAN (R 4.0.2)
    #>  colorspace    1.4-1      2019-03-18 [1] CRAN (R 4.0.2)
    #>  crayon        1.3.4      2017-09-16 [1] CRAN (R 4.0.2)
    #>  DBI           1.1.0      2019-12-15 [1] CRAN (R 4.0.2)
    #>  dbplyr        1.4.4      2020-05-27 [1] CRAN (R 4.0.2)
    #>  desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.2)
    #>  devtools      2.3.1      2020-07-21 [1] CRAN (R 4.0.2)
    #>  digest        0.6.25     2020-02-23 [1] CRAN (R 4.0.2)
    #>  dplyr       * 1.0.1      2020-07-31 [1] CRAN (R 4.0.2)
    #>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.2)
    #>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.2)
    #>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.2)
    #>  forcats     * 0.5.0      2020-03-01 [1] CRAN (R 4.0.2)
    #>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)
    #>  generics      0.0.2      2018-11-29 [1] CRAN (R 4.0.2)
    #>  ggplot2     * 3.3.2      2020-06-19 [1] CRAN (R 4.0.2)
    #>  glue          1.4.1      2020-05-13 [1] CRAN (R 4.0.2)
    #>  gtable        0.3.0      2019-03-25 [1] CRAN (R 4.0.2)
    #>  haven         2.3.1      2020-06-01 [1] CRAN (R 4.0.2)
    #>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.2)
    #>  hms           0.5.3      2020-01-08 [1] CRAN (R 4.0.2)
    #>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.0.2)
    #>  httr          1.4.2      2020-07-20 [1] CRAN (R 4.0.2)
    #>  jsonlite      1.7.0      2020-06-25 [1] CRAN (R 4.0.2)
    #>  knitr         1.29       2020-06-23 [1] CRAN (R 4.0.2)
    #>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.2)
    #>  lubridate     1.7.9      2020-06-08 [1] CRAN (R 4.0.2)
    #>  magrittr      1.5        2014-11-22 [1] CRAN (R 4.0.2)
    #>  memoise       1.1.0      2017-04-21 [1] CRAN (R 4.0.2)
    #>  modelr        0.1.8      2020-05-19 [1] CRAN (R 4.0.2)
    #>  munsell       0.5.0      2018-06-12 [1] CRAN (R 4.0.2)
    #>  pillar        1.4.6      2020-07-10 [1] CRAN (R 4.0.2)
    #>  pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 4.0.2)
    #>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.2)
    #>  pkgload       1.1.0      2020-05-29 [1] CRAN (R 4.0.2)
    #>  pointblank  * 0.5.0.9000 2020-08-17 [1] local         
    #>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.2)
    #>  processx      3.4.3      2020-07-05 [1] CRAN (R 4.0.2)
    #>  ps            1.3.4      2020-08-11 [1] CRAN (R 4.0.2)
    #>  purrr       * 0.3.4      2020-04-17 [1] CRAN (R 4.0.2)
    #>  R6            2.4.1      2019-11-12 [1] CRAN (R 4.0.2)
    #>  Rcpp          1.0.5      2020-07-06 [1] CRAN (R 4.0.2)
    #>  readr       * 1.3.1      2018-12-21 [1] CRAN (R 4.0.2)
    #>  readxl        1.3.1      2019-03-13 [1] CRAN (R 4.0.2)
    #>  remotes       2.2.0      2020-07-21 [1] CRAN (R 4.0.2)
    #>  reprex        0.3.0      2019-05-16 [1] CRAN (R 4.0.2)
    #>  rlang         0.4.7      2020-07-09 [1] CRAN (R 4.0.2)
    #>  rmarkdown     2.3        2020-06-18 [1] CRAN (R 4.0.2)
    #>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 4.0.2)
    #>  rvest         0.3.6      2020-07-25 [1] CRAN (R 4.0.2)
    #>  scales        1.1.1      2020-05-11 [1] CRAN (R 4.0.2)
    #>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.2)
    #>  stringi       1.4.6      2020-02-17 [1] CRAN (R 4.0.0)
    #>  stringr     * 1.4.0      2019-02-10 [1] CRAN (R 4.0.2)
    #>  testthat      2.3.2      2020-03-02 [1] CRAN (R 4.0.2)
    #>  tibble      * 3.0.3      2020-07-10 [1] CRAN (R 4.0.2)
    #>  tidyr       * 1.1.1      2020-07-31 [1] CRAN (R 4.0.2)
    #>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.0.2)
    #>  tidyverse   * 1.3.0      2019-11-21 [1] CRAN (R 4.0.2)
    #>  usethis       1.6.1      2020-04-29 [1] CRAN (R 4.0.2)
    #>  vctrs         0.3.2      2020-07-15 [1] CRAN (R 4.0.2)
    #>  withr         2.2.0      2020-04-20 [1] CRAN (R 4.0.2)
    #>  xfun          0.16       2020-07-24 [1] CRAN (R 4.0.2)
    #>  xml2          1.3.2      2020-04-23 [1] CRAN (R 4.0.2)
    #>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)
    #> 
    #> [1] C:/R/R-4.0.2/library

**Comment by rich-iannone** [comment]
Thanks for reporting this! Likely, there are a few problems with the `get_sundered_data()` function under some low data conditions. I need to identify all of these and guard against this bad subsetting. Once good fixes are in place, a secondary goal is to add testthat tests for all the edge cases. 

Beyond this: make it more clear how the split is occurring (i.e., which validation steps are being used), perhaps though a console message.

Thanks again, this should be fixed soon!

**Comment by nickv9** [comment]
Thanks for the quick response @rich-iannone !

If interested, here is a little context.....

I was planning to use `get_sundered_data()` to create a data set that would enable me to easily explore differences between rows that failed a test, and rows that passed. 

In lieu of a fix to  `get_sundered_data()`, I think I can work around this easily by splitting on `agent$validation_set$tbl_checked[[1]][[1]]$pb_is_good_`. Something like this would be the start of this....

``` r
library(tidyverse)
library(pointblank)

agent <-
  create_agent(tbl = small_table) %>%
  col_vals_between(
    vars(c), left = vars(a), right = vars(d),
    na_pass = TRUE
  ) %>%
  interrogate()

agent$validation_set$tbl_checked[[1]][[1]] %>% 
  rename(pass = pb_is_good_) %>% 
  mutate(test = agent$validation_set$brief)
```

    #> # A tibble: 13 x 10
    #>    date_time           date           a b         c      d e     f     pass 
    #>    <dttm>              <date>     <int> <chr> <dbl>  <dbl> <lgl> <chr> <lgl>
    #>  1 2016-01-04 11:00:00 2016-01-04     2 1-bc~     3  3423. TRUE  high  TRUE 
    #>  2 2016-01-04 00:32:00 2016-01-04     3 5-eg~     8 10000. TRUE  low   TRUE 
    #>  3 2016-01-05 13:32:00 2016-01-05     6 8-kd~     3  2343. TRUE  high  FALSE
    #>  4 2016-01-06 17:23:00 2016-01-06     2 5-jd~    NA  3892. FALSE mid   TRUE 
    #>  5 2016-01-09 12:36:00 2016-01-09     8 3-ld~     7   284. TRUE  low   FALSE
    #>  6 2016-01-11 06:15:00 2016-01-11     4 2-dh~     4  3291. TRUE  mid   TRUE 
    #>  7 2016-01-15 18:46:00 2016-01-15     7 1-kn~     3   843. TRUE  high  FALSE
    #>  8 2016-01-17 11:27:00 2016-01-17     4 5-bo~     2  1036. FALSE low   FALSE
    #>  9 2016-01-20 04:30:00 2016-01-20     3 5-bc~     9   838. FALSE high  TRUE 
    #> 10 2016-01-20 04:30:00 2016-01-20     3 5-bc~     9   838. FALSE high  TRUE 
    #> 11 2016-01-26 20:07:00 2016-01-26     4 2-dm~     7   834. TRUE  low   TRUE 
    #> 12 2016-01-28 02:51:00 2016-01-28     2 7-dm~     8   108. FALSE low   TRUE 
    #> 13 2016-01-30 11:23:00 2016-01-30     1 3-dk~    NA  2230. TRUE  high  TRUE 
    #> # ... with 1 more variable: test <chr>

**Comment by rich-iannone** [comment]
@nickv9 Thanks for these additional notes and your patience while a fix was implemented (very glad you discovered a workaround in the meantime). This should be fixed now, would you mind trying your original code again on the GitHub version of the package? Thanks!

**Comment by nickv9** [comment]
Works great, thanks for the quick response. What I am trying to accomplish would be made easier with an enhancement - ill create another issue for that.

Thanks again!
