### ISSUE TITLE
all_passed and n_passed handle NA values differently for some interrogation tests

### ISSUE THREAD

**Issue by ekothe** [rstudio/pointblank#15]
Different parts of the interrogration report handle NA values differently. This is apparent for col_vals_between and col_vals_in_set (as well as presumably effecting other tests I don't currently use).

I have a simple dataframe that includes missing values and check that all values of column B are between 0 and 20.
```
df<-structure(list(A = c(NA, 2L, 3L, 4L, 5L, 6L, NA, 8L, 9L, NA), 
               B = c(11L, 12L, NA, NA, NA, NA, 17L, 18L, 19L, 20L), 
               C = c(NA, NA, NA, 24L, NA, 26L, NA, 28L, NA, 30L)), 
               .Names = c("A",  "B", "C"), row.names = c(NA, -10L), class = "data.frame")

agent <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
    col_vals_between( 
    column = B,
    left = 0,
    right = 20)
  interrogate()

all_passed(agent)
get_interrogation_summary(agent)
```

`all_passed()` returns `TRUE` but `get_interrogation_summary()` reports that 60% of rows are not within range. 

```
# A tibble: 1 x 12
  tbl_name db_type  assertion_type   column value regex all_passed     n n_passed f_passed action brief            
  <chr>    <chr>    <chr>            <chr>  <dbl> <chr> <lgl>      <dbl>    <dbl>    <dbl> <chr>  <chr>            
1 df       local_df col_vals_between B         NA NA    TRUE          10        6      0.6 NA     Expect that valu~
```

This occurs because the NAs are counted as failing in some calculations but not in others. 

I can partially control this behaviour by adding a pre-condition to only apply this test to rows where B is not NA.

```
agent <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
  col_vals_between(
    column = B,
    left = 0,
    right = 20,
    preconditions = is.na(B) == FALSE) %>%
  interrogate()
```
But this becomes tedious when applying testing a large number of columns where NAs should not be counted as failing (since each would require a pre-condition that refers to the relevant column by name).  

It's also not apparent whether I could specify that NAs should be counted as **not** in range (except by using a different test). This is a problem if I want the to trigger a warning or notification based on the joint failure rate of NAs and out of range values.

The ability to include or exclude NAs from any given test (as in the example below)  would improve the usability of this function and add consistency between the n_passed and all_passed values.

```
agent <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
  col_vals_between(
    column = B,
    left = 0,
    right = 20,
    na_as_in_range = TRUE) %>%
  interrogate()
```

**Comment by rich-iannone** [comment]
@ekothe Thanks so much for getting to the core of the problem. I'd noticed the discrepency between `all_passed` and `n_passed` before but didn't investigate further. I made a few fixes (this again removes the `mutate_()` call and instead uses the `mutate()`/`case_when()` combo).

I liked your idea about having an extra argument for whether to consider `NA`s as belonging in the range. I actually added 2 args: one for NA and another for NaN. I don't really know if this is a good idea. I mean, there may be cases where you would distinguish, but maybe it could be one arg that includes both. The extra args are for both the `col_vals_between()` and `col_vals_not_between()` functions.

Here are some examples of how this all works now:

```
library(pointblank)

df <-
  structure(list(A = c(NA, 2L, 3L, 4L, 5L, 6L, NA, 8L, 9L, NA), 
                 B = c(11L, 12L, 13L, NA, NA, NA, 17L, 18L, 19L, 20L), 
                 C = c(NA, NA, NA, 24L, NA, 26L, NA, 28L, NA, 30L)), 
            .Names = c("A",  "B", "C"), row.names = c(NA, -10L),
            class = "data.frame")

#
# Tests with `col_vals_between()`
#

agent_between_1 <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
  col_vals_between( 
    column = B,
    left = 0,
    right = 20,
    incl_na = FALSE # default is FALSE
    ) %>%
  interrogate()

all_passed(agent_between_1) # FALSE
get_interrogation_summary(agent_between_1)
#> # A tibble: 1 x 12
#>   tbl_name db_type  assertion_type   column value regex all_passed     n n_passed
#>   <chr>    <chr>    <chr>            <chr>  <dbl> <chr> <lgl>      <dbl>    <dbl>
#> 1 df       local_df col_vals_between B         NA NA    FALSE         10        7
#> # ... with 3 more variables: f_passed <dbl>, action <chr>, brief <chr>

agent_between_2 <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
  col_vals_between( 
    column = B,
    left = 0,
    right = 20,
    incl_na = TRUE
    ) %>%
  interrogate()

all_passed(agent_between_2) # TRUE
get_interrogation_summary(agent_between_2)
#> # A tibble: 1 x 12
#>   tbl_name db_type  assertion_type   column value regex all_passed     n n_passed
#>   <chr>    <chr>    <chr>            <chr>  <dbl> <chr> <lgl>      <dbl>    <dbl>
#> 1 df       local_df col_vals_between B         NA NA    TRUE          10       10
#> # ... with 3 more variables: f_passed <dbl>, action <chr>, brief <chr>

#
# Tests with `col_vals_not_between()`
#

agent_outside_1 <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
  col_vals_not_between( 
    column = A,
    left = 40,
    right = 60,
    incl_na = FALSE # default is TRUE
    ) %>%
  interrogate()

all_passed(agent_outside_1) # FALSE
get_interrogation_summary(agent_outside_1)
#> # A tibble: 1 x 12
#>   tbl_name db_type  assertion_type       column value regex all_passed     n n_passed
#>   <chr>    <chr>    <chr>                <chr>  <dbl> <chr> <lgl>      <dbl>    <dbl>
#> 1 df       local_df col_vals_not_between A         NA NA    FALSE         10        7
#> # ... with 3 more variables: f_passed <dbl>, action <chr>, brief <chr>


agent_outside_2 <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
  col_vals_not_between( 
    column = A,
    left = 40,
    right = 60,
    incl_na = TRUE # default is TRUE
    ) %>%
  interrogate()

all_passed(agent_outside_2)
get_interrogation_summary(agent_outside_2)
#> # A tibble: 1 x 12
#>   tbl_name db_type  assertion_type       column value regex all_passed     n n_passed
#>   <chr>    <chr>    <chr>                <chr>  <dbl> <chr> <lgl>      <dbl>    <dbl>
#> 1 df       local_df col_vals_not_between A         NA NA    TRUE          10       10
#> # ... with 3 more variables: f_passed <dbl>, action <chr>, brief <chr>

```

I changed the code in a few places:
 - `utils.R`: the `create_validation_step()` was changed to have the `incl_na` and `incl_nan` arguments
-  `col_vals_between()` and `col_vals_between()` now have the `incl_na` and `incl_nan` arguments as well; the arg defaults are different between them 
 -  `interrogate.R`: the interrogate function now has this:

```
table %>%
          dplyr::mutate(pb_is_good_ = case_when(
            rlang::UQ(column) >= left & rlang::UQ(column) <= right ~ TRUE,
            rlang::UQ(column) < left | rlang::UQ(column) > right ~ FALSE,
            is.na(rlang::UQ(column)) & incl_na ~ TRUE,
            is.na(rlang::UQ(column)) & incl_na == FALSE ~ FALSE,
            is.nan(rlang::UQ(column)) & incl_nan ~ TRUE,
            is.nan(rlang::UQ(column)) & incl_nan == FALSE ~ FALSE
          ))
```

Weird spot to ask but would you like to have write access to the repo? If you're interested in doing more (and would like to implement things faster) this could be easier. Plus you can make yourself a package author. No pressure, just wanted to ask if you're interested!

**Comment by ekothe** [comment]
@rich-iannone You've only implemented these in col_vals_between() and col_vals_not_between() so far right?

If I notice any other functions I'll let you know (and potentially try and fix with a pull request).

**Comment by rich-iannone** [comment]
@ekothe that's right, just those two functions. This approach probably makes sense with `col_vals_gt()` and similar. I would definitely appreciate a PR, thanks again.

**Comment by ekothe** [comment]
@rich-iannone It looks like this is actually affecting all functions that test column values that are not specifically designed to test of the value is null (i.e. `col_vals_in_set`, `col_vals_not_between`, `col_vals_not_in_set`, `col_vals_lt`, `col_vals_equal`, `col_vals_gt`, `col_vals_lte`, `col_vals_not_equal`, `col_vals_gte`, `col_vals_regex`). Given how the single operator tests are written and the way that the defaults for %in% work with NAs, I'm not sure if they way that you've implemented the solutions for col_vals_between and col_vals_not_between are easily scalable to the other tests. 

One option would seem to be applying the incl_NA as part of the precondition filter since that's evaluated earlier and then would apply to all of the other functions en masse. However, I'm not sure if that would have unexpected side effects for other tests.

**Comment by vhh711** [comment]
## Prework

* [ X] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/pointblank/blob/main/.github/CONTRIBUTING.md).
* [ X] If there is [already a relevant issue](https://github.com/rstudio/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question

I'm not sure if my issue is tied to this, but the validation function I have a question about is mentioned here. 

I'm validating that two columns contain equal values. Both columns have NA observations and numeric observations. I'm encountering that observations where both columns have an NA fail the validation step. When I enable the `na_pass = TRUE` argument, the rows no longer fail the validation step. I was concerned this might pass through rows where one column's observation is a numeric value and the comparison column has an NA. So, I ran a simple test, and indeed the `na_pass = TRUE` argument passes rows where one observation is a number and the other is an NA. 

Am I misunderstanding how the function interprets or treats NAs in relation to numeric values?
Is this the intended behavior of the function?
Would utilizing the preconditions argument address this issue? Could I simply mutate the NA values to equal some number which would then give me an accurate pass/fail?
Or is this a bug?

## Reproducible example

* [ X] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ X] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ X] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ X] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

**No `na_pass `argument**
```
df <- data.frame(
  a = c(2, 3, NA, 4, 5, NA),
  b = c(2, 4, NA, 4, 5, 1)
)

al = action_levels(warn_at = 1) 

agent <- create_agent(
  tbl = df,
  tbl_name = "Are column values equal",
  actions = al
  ) %>% 
  col_vals_equal(
    columns = a,
    value = vars(b),
    label = "Do values match?"
  ) %>% interrogate()

agent
```
![image](https://github.com/rstudio/pointblank/assets/88150730/39ff6991-c0f0-43ab-9000-05ec500ac380)

As you can see in the above screenshot, 3 rows fail. However, I expected two rows to fail. Is this the expected behavior for `col_vals_equal()`?

**Using `na_pass `argument**
```
df <- data.frame(
  a = c(2, 3, NA, 4, 5, NA),
  b = c(2, 4, NA, 4, 5, 1)
)

al = action_levels(warn_at = 1) 

agent <- create_agent(
  tbl = df,
  tbl_name = "Are column values equal",
  actions = al
  ) %>% 
  col_vals_equal(
    columns = a,
    value = vars(b),
    label = "Do values match?",
    na_pass = TRUE
  ) %>% interrogate()

agent
```
![image](https://github.com/rstudio/pointblank/assets/88150730/6a889a9d-aa96-4d9c-a837-42c44068cf83)

As you can see in the above screenshot only 1 row fails, but I expected two to fail.
