### ISSUE TITLE
Enhance get_sundered_data() to pull all pass and fail results together

### ISSUE THREAD

**Issue by nickv9** [rstudio/pointblank#152]
It would be great to enhance `get_sundered_data()` to add an option to the, "type," parameter, perhaps called, "all" that would add a column, perhaps defaulting to, "test_result" that indicates whether the test passed or failed.

I'd look to replace this....

``` r
library(tidyverse)
library(pointblank)

agent <-
  create_agent(tbl = small_table) %>%
  col_vals_between(
    vars(c), left = vars(a), right = vars(d),
    na_pass = TRUE
  ) %>%
  interrogate()

# start of what I'd look to replace
pass_cases <- 
  agent %>% 
  get_sundered_data(type = "pass") %>% 
  mutate(test_result = "pass")

fail_cases <- 
  agent %>% 
  get_sundered_data(type = "fail") %>% 
  mutate(test_result = "fail")

results <- 
  pass_cases %>% 
  bind_rows(fail_cases)
# end of what I'd look to replace

results %>% 
  glimpse()
```

    #> Rows: 13
    #> Columns: 9
    #> $ date_time   <dttm> 2016-01-04 11:00:00, 2016-01-04 00:32:00, 2016-01-06 1...
    #> $ date        <date> 2016-01-04, 2016-01-04, 2016-01-06, 2016-01-11, 2016-0...
    #> $ a           <int> 2, 3, 2, 4, 3, 3, 4, 2, 1, 6, 8, 7, 4
    #> $ b           <chr> "1-bcd-345", "5-egh-163", "5-jdo-903", "2-dhe-923", "5-...
    #> $ c           <dbl> 3, 8, NA, 4, 9, 9, 7, 8, NA, 3, 7, 3, 2
    #> $ d           <dbl> 3423.29, 9999.99, 3892.40, 3291.03, 837.93, 837.93, 833...
    #> $ e           <lgl> TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRU...
    #> $ f           <chr> "high", "low", "mid", "mid", "high", "high", "low", "lo...
    #> $ test_result <chr> "pass", "pass", "pass", "pass", "pass", "pass", "pass",...

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

with

``` r
results <- 
  agent %>% 
  get_sundered_data(type = "all")
```

**Comment by rich-iannone** [comment]
Thanks for the detailed notes here! This can definitely be done. I might even go one step further than this (later on, not right away) and have another option that creates logical flag columns (showing pass/fail) by validation step (keyed by the new `step_id` value). For now though, I could definitely add the above feature.

**Comment by rich-iannone** [comment]
@nickv9 I made the changes but decided on naming the new `type` option as `combined`.

Now this should work:

```r
library(pointblank)

create_agent(tbl = small_table) %>%
  col_vals_between(
    vars(c), left = vars(a), right = vars(d),
    na_pass = TRUE
  ) %>%
  interrogate() %>%
  get_sundered_data(type = "combined")
```

```
── Interrogation Started - there is a single validation step ───────────
✓ Step 1: OK.

── Interrogation Completed ─────────────────────────
# A tibble: 13 x 9
   date_time           date           a b           c      d e     f     .pb_combined
   <dttm>              <date>     <int> <chr>   <dbl>  <dbl> <lgl> <chr> <chr>       
 1 2016-01-04 11:00:00 2016-01-04     2 1-bcd-…     3  3423. TRUE  high  pass        
 2 2016-01-04 00:32:00 2016-01-04     3 5-egh-…     8 10000. TRUE  low   pass        
 3 2016-01-05 13:32:00 2016-01-05     6 8-kdg-…     3  2343. TRUE  high  fail        
 4 2016-01-06 17:23:00 2016-01-06     2 5-jdo-…    NA  3892. FALSE mid   pass        
 5 2016-01-09 12:36:00 2016-01-09     8 3-ldm-…     7   284. TRUE  low   fail        
 6 2016-01-11 06:15:00 2016-01-11     4 2-dhe-…     4  3291. TRUE  mid   pass        
 7 2016-01-15 18:46:00 2016-01-15     7 1-knw-…     3   843. TRUE  high  fail        
 8 2016-01-17 11:27:00 2016-01-17     4 5-boe-…     2  1036. FALSE low   fail        
 9 2016-01-20 04:30:00 2016-01-20     3 5-bce-…     9   838. FALSE high  pass        
10 2016-01-20 04:30:00 2016-01-20     3 5-bce-…     9   838. FALSE high  pass        
11 2016-01-26 20:07:00 2016-01-26     4 2-dmx-…     7   834. TRUE  low   pass        
12 2016-01-28 02:51:00 2016-01-28     2 7-dmx-…     8   108. FALSE low   pass        
13 2016-01-30 11:23:00 2016-01-30     1 3-dka-…    NA  2230. TRUE  high  pass 
```

With this pattern in place, I can later extend the function with a `flagged` type.

**Comment by nickv9** [comment]
Thanks, working on giving it a shot.

Re-running my rmarkdown documents with the validations seems to be taking MUCH longer than just yesterday(before I installed the latest github version).

NOTE: I am not yet running `get_sundered_data()` much less using the "combined" option.

`interrogate()` seems to be the culprit. Are you seeing any significant performance drop in your testing?

My data set has about 481k rows and 33 columns.

**Comment by nickv9** [comment]
Definitely seems like a significant degradation in performance.
I rolled back to the CRAN binary version and `interogate()` using `col_vals_not_in_set()` takes less than 1 second.
Going to either the latest github version or the source version on CRAN results in the same operation taking 30s.
I'll see if I can put together a reprex quickly and open a new issue.
