### ISSUE TITLE
col_exists handling of multiple columns

### ISSUE THREAD

**Issue by ekothe** [rstudio/pointblank#18]
The description for col_exists implies that it can handle multiple columns. However the method for doing this is not apparent. 

`col_exists(column = c(start_date, age))` looks for a column called "c(start_date, age)"

`col_exists(column = c("start_date", "age"))` looks for a column called c('start_date', 'age')

Given this function isn't fully documented I'm not sure if I'm missing something. Is there a way to pass a vector of column names to this function?

**Comment by rich-iannone** [comment]
Sorry it took awhile to get to this. I've modified this function to accept multiple columns. However, the implementation is quite different than in the other functions. In `cols_exist()` (renamed to imply that the standard case is to check for multiple columns), we can pass multiple column names (`cols`) as a vector, or, as bare names in `vars()` (reexported from **dplyr**).

```r
library(pointblank)

df <-
  structure(list(A = c(NA, 2L, 3L, 4L, 5L, 6L, NA, 8L, 9L, NA), 
                 B = c(11L, 12L, 13L, NA, NA, NA, 17L, 18L, 19L, 20L), 
                 C = c(NA, NA, NA, 24L, NA, 26L, NA, 28L, NA, 30L)), 
            .Names = c("A",  "B", "C"), row.names = c(NA, -10L),
            class = "data.frame")


# Test with a vector of columns
agent_1 <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
  cols_exist(cols = c("A", "B", "C", "D")) %>%
  interrogate()

agent_1

# Test with a column names in `vars()`
agent_2 <-
  create_agent() %>%
  focus_on(tbl_name = "df") %>%
  cols_exist(cols = vars(A, B, C, D)) %>%
  interrogate()

agent_2
```

In both cases, we get 3 passing validations and 1 failing.

I'm also thinking that the other functions should adopt `vars()` to express column names. It's pretty standard in **dplyr** and **ggplot** and wouldn't be surprising to most users.
