### ISSUE TITLE
Unclear how to specify a negative condition conjointly

### ISSUE THREAD

**Issue by daranzolin** [rstudio/pointblank#195]
I am perhaps missing something, but it's difficult to express a negative joint condition across rows. For example, I want to verify that if var1 is "J", var2 should be **neither** "F" or "N". So I need the last two rows and only the last two rows to fail here:

``` r
library(pointblank)

tbl <- dplyr::tibble(
  var1 = c("J", "J", "J", "A", "J", "J"),
  var2 = c("R", "R", "R", "B", "F", "N")
)

tbl %>% 
  conjointly(
    ~ col_vals_equal(., vars(var1), "J"),
    ~ col_vals_not_in_set(., vars(var2), c("F","N"))
  ) 
```

    #> Error: Exceedance of failed test units where there should have been conjoint 'pass' units across the following expressions: `~col_vals_equal(., vars(var1), "J")`, `~col_vals_not_in_set(., vars(var2), c("F", "N"))`.
    #> The `conjointly()` validation failed beyond the absolute threshold level (1).
    #> * failure level (3) >= failure threshold (1)

<sup>Created on 2020-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Would a batch of `*_not_conjointly` functions be unnecessary? I feel like I'm missing something simple.

**Comment by rich-iannone** [comment]
What you want here is something in `preconditions`. This will work:

```r
library(pointblank)

tbl <- dplyr::tibble(
  var1 = c("J", "J", "J", "A", "J", "J"),
  var2 = c("R", "R", "R", "B", "F", "N")
)

tbl %>%
  col_vals_not_in_set(
    vars(var2), c("F","N"),
    preconditions = ~ . %>% dplyr::filter(var1 == "J")
  )
```

```
 Error: Exceedance of failed test units where values in `var2` should not have been in the set of `F`, `N`.
The `col_vals_not_in_set()` validation failed beyond the absolute threshold level (1).
* failure level (2) >= failure threshold (1) 
```

What this is doing is mutating the target table just for that validation step. The `~ . %>% dplyr::filter(var1 == "J")` expression in `preconditions` is a functional sequence that filters the target table to just contain rows where `var1` is `"J"`. Then, the single `col_vals_not_in_set()` step works well here (no need for `conjointly()`).

**Comment by daranzolin** [comment]
Aha! Thanks for the thorough explanation! 🙌
