### ISSUE TITLE
Compare to assertr?

### ISSUE THREAD

**Issue by briatte** [rstudio/pointblank#2]
Would it be useful to list the specificities and strengths of the package w/r/t the [assert and assertive packages](http://ropensci.org/blog/blog/2017/04/11/assertr), which perform similar tasks?

**Comment by rich-iannone** [comment]
This is a good idea. It may take some time since I'd have to try out that package and several others (at least 3 other ones) to assess the features of each. 

Thanks for the suggestion.

**Comment by rich-iannone** [comment]
This is now done in https://github.com/rich-iannone/pointblank/commit/ad6bad21280a978df232fbe8966c85f3c9e4aa4f.
