### ISSUE TITLE
Function to read a collection of saved validations and make a report

### ISSUE THREAD

**Issue by michelefgd** [rstudio/pointblank#203]
Thank you for making this package. It really is incredible!

 I have a request that I hope you consider a good idea. I have a workflow where the validation is performed daily and saved to a directory. We are very interested in tracking validation metrics over time. So, the validation report would be one that has a bar graph for each validation step. At least for our purposes, this would be incredibly valuable. Thank you Rich.

**Comment by rich-iannone** [comment]
Great idea! Will definitely do this. Similar to https://github.com/rich-iannone/pointblank/issues/59.
