### ISSUE TITLE
Have an option to skip a validation step if the target column is missing

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/pointblank#219]
It can happen that a column isn't available for a validation check in some circumstances. Further to this, it might be difficult to check for the existence of the column (and it might have to be done outside of the pointblank API). The validation step should still be present but having the interrogation risk failure and possibly trigger some undesired notification is not ideal.

There is an `active` argument which skips a validation step if the value is `FALSE`. If we make available a helper function that automatically skips a step based on the presence of the target column, the aforementioned situation can be better managed. The helper function might be named `if_col_present()`, and it should be allowed for use in `active` arg of each validation function that operates on a target column.

**Comment by tylerlittlefield** [comment]
Is it possible for this to work with `info_column()` and other informant functions? My use case is that I am iterating over numerous datasets that all (roughly) share the same structure. Of course, some columns are missing here and there and so the informant stops and errors out when trying to provide information on a column that doesn't exist.

Although, I just realized I can use `tryCatch` for this with something like:

```r
... %>%
tryCatch(
  expr = {
    info_columns(
      columns = "foo",
      info = "blah blah"
    )
  }, error = function(e) .
) %>%
...
```

**Comment by rich-iannone** [comment]
@tyluRp it's not possible right now but I think a lot of the semantics for validation should be available on the table information side, so, it's something that would be a great feature!

Could you open a new issue for this?

**Comment by tylerlittlefield** [comment]
Done! #338
