### ISSUE TITLE
`focus_on` can fail to get the right local dataframe

### ISSUE THREAD

**Issue by karldw** [rstudio/pointblank#23]
Here's an example:
``` r

library(pointblank)
# Copied from the docs, but wrapped in a function
fn <- function() {
  my_df <- data.frame(a = c(5, 4, 3, 5, 1, 2))
  
  agent <- create_agent() %>%
    focus_on(tbl_name = "my_df") %>%
    col_vals_lt(
      column = a,
      value = 6) %>%
    interrogate()
  
  all_passed(agent)
}
fn()
#> Error in get(tbl_name): object 'my_df' not found
```

<sup>Created on 2019-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note that if a `my_df` object existed in the global scope, `focus_on` would use the global object instead. I think this behavior is happening because `focus_on` uses `get` instead of `dynGet` [here](https://github.com/rich-iannone/pointblank/blob/1eca023d41cfd2c775b961f53d3ef665c3534c9a/R/focus_on.R#L140).

**Comment by rich-iannone** [comment]
Thanks for posting this. I’ll make this change and some tests to ensure that searching for the table object is also successful within functions.
