### ISSUE TITLE
Translate validation checks into human-readable descriptions

### ISSUE THREAD

**Issue by emilyriederer** [rstudio/pointblank#233]
## Prework

- [x] Read and abide by **pointblank**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rich-iannone/pointblank/issues) (both open and closed).

## Proposal

`pointblank` creates amazing, aesthetic documentation. However, it might also be useful to be able to automate documentation in human-readable plain text (e.g. details in a data dictionary). To enable this, it could be useful to have some sort of `translate()` function that can parse validation checks. For example:

```
translate(col_vals_between(agent, starts_with("N"), left = 0, right = 9, inclusive = c(TRUE, FALSE)))
```

might return something like 

> Column between 0 (inclusive) and 9 (exclusive)

I can imagine multiple ways that this function could work. For example, such a function might either take the validation functions directly (as shown above) or it could take the `agent` object and return a dataframe with one row per check and one column with the "code" version and one with the plaintext.

**Comment by rich-iannone** [comment]
Great news! We already have some infrastructure for this in **pointblank** with the unfortunately named autobriefs. Take a look at this file https://github.com/rich-iannone/pointblank/blob/master/data-raw/translations_source.yml, it translates each type of validation to easily readable text (with gluestrings, so it has the requisite values and columns names as well). 

I can see lots of ways to integrate the validations into the data dictionary (and vice versa) but, right now, we can extract the built table of data validations with something like this:

```r
agent <- 
  create_agent(
    read_fn = ~ small_table,
    label = "An example.",
    actions = action_levels(warn_at = 0.10, stop_at = 0.25, notify_at = 0.35)
  ) %>%
  col_exists(vars(date, date_time)) %>%
  col_vals_regex(
    vars(b), "[0-9]-[a-z]{3}-[0-9]{3}"
  ) %>%
  rows_distinct() %>%
  col_vals_gt(vars(d), 100) %>%
  col_vals_lte(vars(c), 5) %>%
  col_vals_equal(
    vars(d), vars(d),
    na_pass = TRUE
  ) %>%
  col_vals_between(
    vars(c),
    left = vars(a), right = vars(d),
    na_pass = TRUE
  ) %>%
  interrogate()

# This gives us a giant list of everything
x_list <- agent %>% get_agent_x_list()

# Get the `validation_set` list element
validation_set <- x_list$validation_set

validation_set
#> # A tibble: 8 x 28
#>       i step_id sha1  assertion_type column values na_pass preconditions actions label brief active eval_error
#>   <int> <chr>   <chr> <chr>          <list> <list> <lgl>   <list>        <list>  <chr> <chr> <lgl>  <lgl>     
#> 1     1 0001    e9fc… col_exists     <chr … <NULL> NA      <NULL>        <actn_… NA    "Exp… TRUE   FALSE     
#> 2     2 0002    aedd… col_exists     <chr … <NULL> NA      <NULL>        <actn_… NA    "Exp… TRUE   FALSE     
#> 3     3 0003    8f62… col_vals_regex <chr … <chr … FALSE   <NULL>        <actn_… NA    "Exp… TRUE   FALSE     
#> 4     4 0004    8307… rows_distinct  <list… <NULL> NA      <NULL>        <actn_… NA    "Exp… TRUE   FALSE     
#> 5     5 0005    dc6b… col_vals_gt    <chr … <dbl … FALSE   <NULL>        <actn_… NA    "Exp… TRUE   FALSE     
#> 6     6 0006    18ed… col_vals_lte   <chr … <dbl … FALSE   <NULL>        <actn_… NA    "Exp… TRUE   FALSE     
#> 7     7 0007    887c… col_vals_equal <chr … <quos… TRUE    <NULL>        <actn_… NA    "Exp… TRUE   FALSE     
#> 8     8 0008    68e5… col_vals_betw… <chr … <quos… TRUE    <NULL>        <actn_… NA    "Exp… TRUE   FALSE     
#> # … with 15 more variables: eval_warning <lgl>, capture_stack <list>, all_passed <lgl>, n <dbl>, n_passed <dbl>,
#> #   n_failed <dbl>, f_passed <dbl>, f_failed <dbl>, warn <lgl>, notify <lgl>, stop <lgl>, row_sample <dbl>,
#> #   tbl_checked <list>, time_processed <dttm>, proc_duration_s <dbl>

# Get just the briefs
validation_set$brief

#> [1] "Expect that column `date` exists."                                                         
#> [2] "Expect that column `date_time` exists."                                                    
#> [3] "Expect that values in `b` should match the regular expression: `[0-9]-[a-z]{3}-[0-9]{3}`. "
#> [4] "Expect entirely distinct rows across all columns. "                                        
#> [5] "Expect that values in `d` should be > `100`. "                                             
#> [6] "Expect that values in `c` should be <= `5`. "                                              
#> [7] "Expect that values in `d` should be == `d`. "                                              
#> [8] "Expect that values in `c` should be between `a` and `d`. "  
```

I'd definitely enjoy the opportunity to brainstorm over ideas on how this can be repurposed for the reporting. Currently, these show up in the validation report when hovering over items in the `STEP` column .

I can see all of this turning into a bunch of issues where we lay the groundwork with internal functions and then expose better features for reporting!

**Comment by rich-iannone** [comment]
Just added the `?? Question` label to mark this issue as a sort of spike issue where we could come up several concrete issues after some more discussion.

**Comment by emilyriederer** [comment]
Thanks so much @rich-iannone ! I really appreciate the reply, the example, and the awesome feature. This is so perfect that I am wondering if somehow I have seen it before because it is exactly what I was picturing. 

Sorry for opening an issue for something that exists; I went through the docs and had poked around in the `agent` object structure, but didn't think to look into `get_agent_x_list()`. Now I see where it's mentioned in the reference for that function. 

(As a sidenote, I absolutely love how you have it available for so many languages - incredible!)

**Comment by rich-iannone** [comment]
You’re totally welcome and please don’t worry about not seeing it elsewhere (I threw everything but the kitchen sink into this package). 

Also, I’m realizing that the issue checklist is a bit formal and off putting. I put that stuff in the package to satisfy the CII Best Practices badge requirements and the language there really doesn’t sound like me. Basically, don’t ever be afraid to open an issue about anything and don’t worry about searching around first. (I’ll change the language on the issue checklist so it doesn’t sound so formal.)

Let’s keep this issue open so we can discuss interesting ways to use the auto-generating validation descriptors. And let me know if there is anything that could be done to make their extraction easier/better!

**Comment by emilyriederer** [comment]
Oh, I did not interpret it in a bad way at all! It seems totally reasonable to me to ask for some due diligence before asking a question.

Regarding applications, I think there are actually a ton! For context, the two that I was going to use this for in the near term are:

- Translating validation results to plaintext and using `projmgr` to open GitHub issues reporting data errors (to a group of data producers who aren't R users so might prefer the plaintext version over the syntax version). I picture a case where one could both host the Rmd report that `pointblank` generates somewhere as an always on validation any user could look at, but the translation could actually notify publishers of specific issues in a timely fashion (of course, I realize the `blastula` integration already is another way to accomplish this!)
- Documenting what data checks are associated with which variable name prefixes (using `starts_with()`) without evaluating on any actual data (a very very ugly, simplistic version of what I'm talking about is implemented right above the anchor I'm linking to [here](https://emilyriederer.github.io/convo/articles/quickstart-guide.html#beyond-column-names-1))

**Comment by rich-iannone** [comment]
@emilyriederer Circling back to this issue, seems like there's nothing additional to be done here? Does the `get_agent_x_list()` function provide everything that's needed for `convo`?

**Comment by emilyriederer** [comment]
Yes thanks, @rich-iannone ! This is working great for me
