### ISSUE TITLE
Minor error in cojointly() examples documentation

### ISSUE THREAD

**Issue by stevenshrago** [rstudio/pointblank#235]
From: [https://rich-iannone.github.io/pointblank/reference/conjointly.html#examples](url)

The comments in the example state that the first validation test in the group is:

(1) values in `a` are less than `4`

While the rest of the example code shows:

```
    ~ col_vals_lt(., vars(a), 8),
```

Presumably, example text should read:

(1) values in `a` are less than `8`

Incredibly minor, but enough to throw me off for a couple of minutes.

**Comment by rich-iannone** [comment]
Thanks for reporting this. There’s no way I would have found this until working on the `conjointly()` examples again so this helps!

**Comment by rich-iannone** [comment]
Should be fixed now with https://github.com/rich-iannone/pointblank/commit/63cdf02ba9b23b5d6d1754f90fabe81ef43af64c. Thanks!
