### ISSUE TITLE
Is there any way to suppress "Pointblank Information" header at the top of informant output table?

### ISSUE THREAD

**Issue by kj-9** [rstudio/pointblank#251]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question
Is there any way to suppress "Pointblank Information" header at the top of informant output table?

![image](https://user-images.githubusercontent.com/46800811/104188499-ad879380-545c-11eb-80e8-f165026430d2.png)

AS a background, I'm putting 5-10 different informant tables in one page, (This is my subjective opinion but) I feel "Pointblank Information" headers for every table are bit busy and redundant. It would be nice to suppress these headers and make table names stand out more in some cases.

p.s. Thank you for creating this amazing package! I love to use and explore pointblank's features.

**Comment by rich-iannone** [comment]
I agree that the title wouldn't be all that great if it's repeated so much in a single document. I think that options for the header would work well if put in the `get_informant_report()` function. It already has layout and content options like `size`, `lang`, and `locale`.

As far as header options, we could use `"default"`, `"none"`, `"tbl_name"`, or a custom one wrapped in either `md()` or `I()`. Let me know if these options sound good to you!

**Comment by kj-9** [comment]
Thank you for replying and treating this as an enhancement.

> As far as header options, we could use "default", "none", "tbl_name"

This sounds great for me. For "tbl_name", I'm sure you mean displaying table name as a tittle header. That's great fit for my use case.  Still,  I guess placing a message like "this is generated by pointblank" somewhere sparingly as option can be useful.

>or a custom one wrapped in either md() or I()

I'm not sure what these functions achieve in this case for now. I will search these later!

**Comment by rich-iannone** [comment]
You're welcome, thanks for using the package! Yes, the `"tbl_name"` option would provide the name of the table in a monospaced version of the same font. The custom titles being wrapped in `md()` (for using Markdown) or `I()` (meaning identity, or literal text; used so it doesn't collide with the keywords like `"none"`) will be better explained in the documentation once the feature is implemented.

A message in the style of `"generated by pointblank"` might be better in the table footer. It should be opt out, and, include more useful information like the session info. It can be part of a `<details>` tag and revealed on click (saving space). Basically, lots of ideas here!

**Comment by kj-9** [comment]
Thank you for explaining,
I understand that wrapping in `md()`/`I()` offers great flexibility, that's nice!

>A message in the style of "generated by pointblank" might be better in the table footer. It should be opt out, and, include more useful information like the session info. It can be part of a `<details>` tag and revealed on click (saving space). Basically, lots of ideas here!

These ideas are really appealing to me!  Using `<details>` is great for some users who wants to look through multiple informant reports first and check details later. And I'm actually creating a vignette to introduce datasets of my R package using informant reports, that will be great feature for me :smile:

**Comment by rich-iannone** [comment]
This has now been merged in #257. What's been added is the `title` arg in `get_informant_report()` (it's also been added to other `get_*()` functions). The option you're looking for is `title = ":tbl_name:"`. You also have the option to use `glue::glue()` and use something like 

```
title = glue::glue("Information on the `{[informant_obj]$tbl_name}` table").
```

I've decided against having `md()` as an option here because other arguments that accept text automatically transform Markdown to HTML. However, I've included the option to use `I()` to turn off that behavior.

Try it out and let me know if this suits your needs!

**Comment by rich-iannone** [comment]
One more thing, I'll do some work on the `<details>` idea a bit later. It was a little out of scope for this issue but there are some good things in store for that. A separate Issue will be opened.

**Comment by kj-9** [comment]
Thank you very much for this change!
I'll definitely try this out and share my work. 
([Discussions](https://github.com/rich-iannone/pointblank/discussions) may be better place to share my work as example for the community and for further discussions! I'll post there.)

**Comment by rich-iannone** [comment]
Absolutely share anything you like in Discussions. If there are aspects of the workflow that have rough edges (or you have another idea for a feature), let's talk about it there and we could always make a well-defined issue from those discussions!
