### ISSUE TITLE
Loading pointblank prior to tangling with knitr::knit causes knitr::knit to fail.

### ISSUE THREAD

**Issue by SteveLane** [rstudio/pointblank#252]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

When trying to tangle Rmd using `knitr::knit` after loading the `pointblank` library, the code is not tangled at all.

Not sure if this is a `pointblank` issue, or elsewhere, but this is where I nailed it down to in my testing.

## Reproducible example

* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

Reproducible code:

    library(pointblank)

    #> Warning: package 'pointblank' was built under R version 4.0.3

    rmd_text <- "\n---\ntitle: \"Testing pointblank\"\noutput: html_document\n---\n```{r test-chunk}\ny <- 2\ny * 5\n```\n"
    out_temp <- tempfile()
    knitr::knit(text = rmd_text, tangle = TRUE, output = out_temp)

    #> [1] "C:\\Users\\LANES1\\AppData\\Local\\Temp\\RtmpuUqMLO\\file26185eb747d0"

    cat(readLines(out_temp), sep = '\n')

    #> NA
    #> ---
    #> 
    #> NA

<sup>Created on 2021-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()

    #> - Session info ---------------------------------------------------------------
    #>  setting  value                       
    #>  version  R version 4.0.1 (2020-06-06)
    #>  os       Windows 10 x64              
    #>  system   x86_64, mingw32             
    #>  ui       RTerm                       
    #>  language (EN)                        
    #>  collate  English_Australia.1252      
    #>  ctype    English_Australia.1252      
    #>  tz       Australia/Sydney            
    #>  date     2021-01-12                  
    #> 
    #> - Packages -------------------------------------------------------------------
    #>  package     * version date       lib source        
    #>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
    #>  backports     1.1.7   2020-05-13 [1] CRAN (R 4.0.0)
    #>  blastula      0.3.2   2020-05-19 [1] CRAN (R 4.0.3)
    #>  callr         3.4.3   2020-03-28 [1] CRAN (R 4.0.0)
    #>  cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
    #>  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
    #>  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
    #>  devtools      2.3.0   2020-04-10 [1] CRAN (R 4.0.0)
    #>  digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
    #>  dplyr         1.0.0   2020-05-29 [1] CRAN (R 4.0.0)
    #>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
    #>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
    #>  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
    #>  fs            1.4.1   2020-04-04 [1] CRAN (R 4.0.0)
    #>  generics      0.0.2   2018-11-29 [1] CRAN (R 4.0.0)
    #>  glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.0)
    #>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.0)
    #>  htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.0)
    #>  knitr         1.30    2020-09-22 [1] CRAN (R 4.0.3)
    #>  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
    #>  magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.0)
    #>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
    #>  pillar        1.4.4   2020-05-05 [1] CRAN (R 4.0.0)
    #>  pkgbuild      1.0.8   2020-05-07 [1] CRAN (R 4.0.0)
    #>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
    #>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
    #>  pointblank  * 0.6.0   2020-11-20 [1] CRAN (R 4.0.3)
    #>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
    #>  processx      3.4.2   2020-02-09 [1] CRAN (R 4.0.0)
    #>  ps            1.3.3   2020-05-08 [1] CRAN (R 4.0.0)
    #>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
    #>  R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
    #>  remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.3)
    #>  rlang         0.4.6   2020-05-02 [1] CRAN (R 4.0.0)
    #>  rmarkdown     2.6     2020-12-14 [1] CRAN (R 4.0.3)
    #>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
    #>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
    #>  stringi       1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
    #>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
    #>  testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
    #>  tibble        3.0.1   2020-04-20 [1] CRAN (R 4.0.0)
    #>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
    #>  usethis       1.6.3   2020-09-17 [1] CRAN (R 4.0.3)
    #>  vctrs         0.3.1   2020-06-05 [1] CRAN (R 4.0.0)
    #>  withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.0)
    #>  xfun          0.20    2021-01-06 [1] CRAN (R 4.0.3)
    #>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
    #> 
    #> [1] C:/Users/LANES1/R/win-library/4.0
    #> [2] C:/Program Files/R/R-4.0.1/library

</details>

## Expected result

The code in the Rmd text should have been written to the file:

    rmd_text <- "\n---\ntitle: \"Testing pointblank\"\noutput: html_document\n---\n```{r test-chunk}\ny <- 2\ny * 5\n```\n"
    out_temp <- tempfile()
    knitr::knit(text = rmd_text, tangle = TRUE, output = out_temp)
    #> [1] "C:\\Users\\LANES1\\AppData\\Local\\Temp\\RtmpMPPUmo\\file1d48385921a0"
    cat(readLines(out_temp), sep = '\n')
    #> ## ----test-chunk---------------------------------------------------------------
    #> y <- 2
    #> y * 5

<sup>Created on 2021-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> - Session info ---------------------------------------------------------------
    #>  setting  value                       
    #>  version  R version 4.0.1 (2020-06-06)
    #>  os       Windows 10 x64              
    #>  system   x86_64, mingw32             
    #>  ui       RTerm                       
    #>  language (EN)                        
    #>  collate  English_Australia.1252      
    #>  ctype    English_Australia.1252      
    #>  tz       Australia/Sydney            
    #>  date     2021-01-12                  
    #> 
    #> - Packages -------------------------------------------------------------------
    #>  package     * version date       lib source        
    #>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
    #>  backports     1.1.7   2020-05-13 [1] CRAN (R 4.0.0)
    #>  callr         3.4.3   2020-03-28 [1] CRAN (R 4.0.0)
    #>  cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
    #>  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
    #>  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
    #>  devtools      2.3.0   2020-04-10 [1] CRAN (R 4.0.0)
    #>  digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
    #>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
    #>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
    #>  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
    #>  fs            1.4.1   2020-04-04 [1] CRAN (R 4.0.0)
    #>  glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.0)
    #>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.0)
    #>  htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.0)
    #>  knitr         1.30    2020-09-22 [1] CRAN (R 4.0.3)
    #>  magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.0)
    #>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
    #>  pkgbuild      1.0.8   2020-05-07 [1] CRAN (R 4.0.0)
    #>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
    #>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
    #>  processx      3.4.2   2020-02-09 [1] CRAN (R 4.0.0)
    #>  ps            1.3.3   2020-05-08 [1] CRAN (R 4.0.0)
    #>  R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
    #>  remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.3)
    #>  rlang         0.4.6   2020-05-02 [1] CRAN (R 4.0.0)
    #>  rmarkdown     2.6     2020-12-14 [1] CRAN (R 4.0.3)
    #>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
    #>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
    #>  stringi       1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
    #>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
    #>  testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
    #>  usethis       1.6.3   2020-09-17 [1] CRAN (R 4.0.3)
    #>  withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.0)
    #>  xfun          0.20    2021-01-06 [1] CRAN (R 4.0.3)
    #>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
    #> 
    #> [1] C:/Users/LANES1/R/win-library/4.0
    #> [2] C:/Program Files/R/R-4.0.1/library

</details>

**Comment by petrbouchal** [comment]
Just to say I ran into this also, manifested as ropensci/tarchetypes#60 and that specifically it happens with pointblank >= 0.4.0.

Here is a simple reprex of my case, based on an example from tarchetypes' `tar_knitr_deps()`:

```r
library(pointblank)
library(tarchetypes)
lines <- c(
  "---",
  "title: report",
  "output_format: html_document",
  "---",
  "",
  "```{r}",
  "targets::tar_load(data1)",
  "targets::tar_read(data2)",
  "```"
)
report <- tempfile()
writeLines(lines, report)
tarchetypes::tar_knitr_deps(report)

```

Without loading pointblank, the function returns targets detected in the Rmd string, with it, it returns and empty vector. Changing the order in which things are loaded does not matter, nor does loading knitr later on.

My guess would be that the issue appeared somewhere around https://github.com/rich-iannone/pointblank/commit/59630d28e3ea3496eceaeee1ea0b81bcf00a61c0.

**Comment by rich-iannone** [comment]
Thanks @petrbouchal for the closer look into the cause. Some of changes in the commit you references have recently been reversed. So targets should now work well with pointblank. 

@SteveLane  tangling should also work fine now. Sorry for the delay in getting to this fix (and causing the problem in the first place).
