### ISSUE TITLE
Support arrow datasets in `create_informant()`

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/pointblank#255]
## Prework

- [x] Read and abide by **pointblank**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rich-iannone/pointblank/issues) (both open and closed).

## Proposal

Since Spark and DBI dataframes are supported, it would be nice to also support [Arrow datasets](https://arrow.apache.org/docs/r/articles/dataset.html).

Currently, getting the right metadata (row number) requires all the data to be in memory, which defeats the purpose of Arrow datasets (which is why it can't be done using the `read_fn` param). 

Here is what I found when I tried to manually rig the output of `create_informant()`:
- `dims()` can be called on an Arrow dataset object to retrieve the dimensions of the table 
- calling `head()` on an Arrow dataset returns an object from which data types can be extracted (e.g. `head(ds)$columns[[1]]$type`) - these will be Arrow types, not R types, but there is a direct mapping. 
- R data types for columns could also be retrieved by `collect()`-ing the output of the `head()` call.

Additionally, it might also be useful to display the partitioning schema in the informant report - perhaps as an automatically generated `info_section()`?

**Comment by rich-iannone** [comment]
I really like this plan for a new source of data. This'll take a little bit of time since Arrow datasets will need to be supported and tested *everywhere* in pointblank (agent, informant, table scan, in `file_tbl()`) but I'm happy to get this going sooner than later.

Also, thanks for the additional details based on your testing with `create_informant()`. The agent or informant will have to gather metadata about dimensions with the `read_fn` (this is what's done internally with all tables). Having the partitioning be an automatically generated section is a great idea!

**Comment by petrbouchal** [comment]
Thanks - I should add that there surely are smarter ways to get at that metadata - though I haven't yet found any way to get at the partitioning information other than parsing the files listen in the Arrow object.

I aimed at the informant workflow as that seemed easy to implement by itself without grappling with the out-of-memory logic of Arrow - but I understand you want to support it across all workflows. Looking at the documentation for Arrow, I am guessing the backend might yet gain some more ability to perform table operations out of memory, which might be useful for pointblank workflows, so it might even be worth waiting or checking with the authors.

**Comment by rich-iannone** [comment]
I think what I'll do is split this into multiple issues/PRs and gradually add support for Arrow across the different workflows (starting with the informant workflow). I did some re-reading of the Arrow R API docs recently and so I think I'm prepared to start work on this one!

**Comment by rich-iannone** [comment]
Hi @petrbouchal I've got some basic support for Arrow tables in #259 . Would you like to test out the branch? I still need to get extended info about partitioning into the report but it's looking pretty good so far.

**Comment by petrbouchal** [comment]
Hi @rich-iannone Many thanks, that was very quick!

Here is what I am seeing:

- table type capture correctly
- row information captured correctly
- column information not captured

...unless I am missing something obvious?

I also tried this on a large local Arrow dataset with partitioning and the result was the same.

``` r
library(pointblank)
library(arrow)
```

    #> 
    #> Attaching package: 'arrow'

    #> The following object is masked from 'package:utils':
    #> 
    #>     timestamp

``` r
arrow::write_dataset(mtcars, "m", format = "parquet")
m <- arrow::open_dataset("m")

pointblank::create_informant(m)
```

    #> Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
    #> This warning is displayed once every 8 hours.
    #> Call `lifecycle::last_warnings()` to see where this warning was generated.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/1666657/105058571-a53fe180-5a76-11eb-990e-a43349b38186.png">


``` r
# for comparison
pointblank::create_informant(mtcars)
```

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1666657/105058629-b557c100-5a76-11eb-9e25-b58dc42d75a6.png">
(screenshot cut off)


<sup>Created on 2021-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

------------------------------------------------------------------------

**Comment by rich-iannone** [comment]
I've added a commit to hopefully fix this and I now understand that different table classes are present when using `read_parquet()` vs. `open_dataset()`. The change makes it work with both ("Table", "ArrowObject", "R6") and ("FileSystemDataset", "Dataset", "ArrowObject", "R6"). Could you retry with this update?

The ```Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.``` is new in this branch and I haven't yet figured out how to fix that.

**Comment by petrbouchal** [comment]
Am now seeing

``` r
library(pointblank)
library(arrow)
```

    #> 
    #> Attaching package: 'arrow'

    #> The following object is masked from 'package:utils':
    #> 
    #>     timestamp

``` r
arrow::write_dataset(mtcars, "m", format = "parquet")
m <- arrow::open_dataset("m")

pointblank::create_informant(m)
```

    #> Error in names(object) <- nm: 'names' attribute [13] must be the same length as the vector [11]

<sup>Created on 2021-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rich-iannone** [comment]
Sorry about this. The error from your example was reproduced on my system. Made yet more changes and now your example code works (along with my other examples using different reading functions from arrow). Could you get the latest and try once more?

**Comment by petrbouchal** [comment]
Looking good!

**Comment by rich-iannone** [comment]
Excellent, thanks for verifying. I think what I need to do is run more (manual) tests on different input datasets (e.g., with partitioning, parquet/feather, etc.) and see if this is robust.

If it's okay, I think I might hold off a bit on getting the extra metadata (type of partitioning, compression codec, dataset dir location) into the informant. There's really a lot there and I'd say it's a different (but important) body of work. I'll file an issue that describes what needs to be done.

**Comment by petrbouchal** [comment]
That sounds great - thanks again for delving into this!

**Comment by rich-iannone** [comment]
You're welcome! I'll revisit how to better obtain metadata from Arrow datasets (and integrate it into the validation workflows) as Arrow becomes more mature. For now, I'll merge the PR.
