### ISSUE TITLE
interrogate() fails when embed_report = TRUE in create_agent()

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/pointblank#256]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

When calling  `interrogate()` on an agent created with `embed_report = TRUE`, an error is returned. 

## Reproducible example

``` r
library(pointblank)
library(magrittr)
create_agent(mtcars, embed_report = T) %>% 
  col_vals_between(gear, 0, 10) %>% 
  interrogate()
```

    #> Error in if (time_diff_s < 1) {: argument is of length zero

<sup>Created on 2021-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

``` r
devtools::session_info()
```

    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.7      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       Europe/Prague               
    #>  date     2021-01-17                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  ! package     * version    date       lib
    #>  P assertthat    0.2.1      2019-03-21 [?]
    #>  P blastula      0.3.2      2020-05-19 [?]
    #>    callr         3.5.1      2020-10-13 [1]
    #>    cli           2.2.0      2020-11-20 [1]
    #>  P crayon        1.3.4      2017-09-16 [?]
    #>  P desc          1.2.0      2018-05-01 [?]
    #>  P devtools      2.3.0      2020-04-10 [?]
    #>    digest        0.6.27     2020-10-24 [1]
    #>    dplyr         1.0.2      2020-08-18 [1]
    #>    ellipsis      0.3.1      2020-05-15 [1]
    #>  P evaluate      0.14       2019-05-28 [?]
    #>    fansi         0.4.1      2020-01-08 [1]
    #>    fs            1.5.0      2020-07-31 [1]
    #>    generics      0.1.0      2020-10-31 [1]
    #>    glue          1.4.2      2020-08-27 [1]
    #>  P highr         0.8        2019-03-20 [?]
    #>    htmltools     0.5.1      2021-01-12 [1]
    #>  P knitr         1.30       2020-09-22 [?]
    #>  P lifecycle     0.2.0      2020-03-06 [?]
    #>    magrittr    * 2.0.1      2020-11-17 [1]
    #>  P memoise       1.1.0      2017-04-21 [?]
    #>    pillar        1.4.7      2020-11-20 [1]
    #>    pkgbuild      1.2.0      2020-12-15 [1]
    #>  P pkgconfig     2.0.3      2019-09-22 [?]
    #>    pkgload       1.1.0      2020-05-29 [1]
    #>    pointblank  * 0.6.0.9000 2021-01-16 [1]
    #>  P prettyunits   1.1.1      2020-01-24 [?]
    #>    processx      3.4.5      2020-11-30 [1]
    #>    ps            1.5.0      2020-12-05 [1]
    #>  P purrr         0.3.4      2020-04-17 [?]
    #>    R6            2.5.0      2020-10-28 [1]
    #>  P remotes       2.1.1      2020-02-15 [?]
    #>  P renv          0.10.0     2020-05-06 [?]
    #>    rlang         0.4.10     2020-12-30 [1]
    #>  P rmarkdown     2.6        2020-12-14 [?]
    #>  P rprojroot     2.0.2      2020-11-15 [?]
    #>  P sessioninfo   1.1.1      2018-11-05 [?]
    #>    stringi       1.5.3      2020-09-09 [1]
    #>  P stringr       1.4.0      2019-02-10 [?]
    #>    testthat      3.0.1      2020-12-17 [1]
    #>    tibble        3.0.4      2020-10-12 [1]
    #>  P tidyselect    1.1.0      2020-05-11 [?]
    #>  P usethis       1.6.1      2020-04-29 [?]
    #>    vctrs         0.3.6      2020-12-17 [1]
    #>    withr         2.4.0      2021-01-16 [1]
    #>    xfun          0.20       2021-01-06 [1]
    #>  P yaml          2.2.1      2020-02-01 [?]
    #>  source                                  
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  Github (rich-iannone/pointblank@9c6e953)
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #> 
    #> [1] /Users/petr/github/obce-covid19/renv/library/R-4.0/x86_64-apple-darwin17.0
    #> [2] /private/var/folders/c8/pj33jytj233g8vr0tw4b2h7m0000gn/T/RtmppYlt5N/renv-system-library
    #> [3] /private/var/folders/c8/pj33jytj233g8vr0tw4b2h7m0000gn/T/RtmpC28iYC/renv-system-library
    #> 
    #>  P ── Loaded and on-disk path mismatch.

</details>

Looking at a quick debug, this seems to be happening at https://github.com/rich-iannone/pointblank/blob/5edc0dd325ff4764541679aedfd999e324b6d931/R/interrogate.R#L378. Functions called inside `get_agent_report()` expect `agent` to contain a `time_end` element, but this is only assigned to `agent` on line 397, outside the `embed_report == TRUE` condition.

**Comment by rich-iannone** [comment]
Thank you for catching this and reporting on it. I will create a PR with a fix soon and add some tests to ensure this option has some test coverage.
