### ISSUE TITLE
Add functions to check if column values missing from set

### ISSUE THREAD

**Issue by JakeRuss** [rstudio/pointblank#266]
## Question

I'd like to be able to check whether a column value is missing from a set, eg. a date in a column is missing from a range of dates. Not that my date column has an NA/NULL value, rather I'd like to know that "2020-06-30" doesn't appear at all in a specified column. So, how would I check for this in the pointblank workflow?

## Reproducible example

```
library(tibble)
library(pointblank)

df <- tibble(x = letters[1:5])

range_vals <- letters[1:6]

df %>%
  create_agent() %>%
  col_vals_in_set(columns = vars(x), set = range_vals) %>%
  col_vals_not_in_set(columns = vars(x), set = range_vals) %>%
  interrogate()

# f is missing from the set
setdiff(range_vals, df$x)

```
With these two checks I confirm that A-E are in the set of A-F and that there are no values in `x` outside of A-F; both 100% pass/fail. But what I'd really like to be able to identify, is that F does not appear in `x`. Thoughts?

**Comment by rich-iannone** [comment]
How about something like this:

```r
library(tibble)
library(pointblank)

df <- tibble(x = letters[1:5])

range_vals <- letters[1:6]

df %>%
  create_agent() %>%
  conjointly(
    ~ col_vals_in_set(., columns = vars(x), set = range_vals),
    ~ col_vals_not_equal(., columns = vars(x), value = "f")
  ) %>%
  interrogate()
```

What's being checked here is that cells in `x` all belong to the set of `range_vals` *and* the same cells don't have a value of `"f"`. Internally, the `conjointly()` function will create two `T`/`F` columns with results for `col_vals_in_set()` and `col_vals_not_equal()`. Then for each row of these results (corresponding to a cell), any FALSE will make the test unit become FALSE (`AND` operation being used).

Does this work for what you're trying to do?

**Comment by rich-iannone** [comment]
I'm sorry I definitely misunderstood the rationale for this one. You really just want to ensure that all items of a set are present and accounted for. Currently, this is missing from `col_vals_in_set()` and I think it needs to gain the `complete` and `in_order` arguments that `col_schema_match()` has for presence of column names.

I'll turn this question into a feature request!

**Comment by JakeRuss** [comment]
Thank you for looking into it, but this is not quite what I had in mind. I ran that code and the result was 5 passing checks and that makes sense, A-E are part of my reference set and are not "F". 

Ideally though, I'd like to be able to perform a check where the agent expects all 6 letters should have at least one entry and report to me that `x` does not have an F entry. I'd also like to not have to hardcode F into the check/test. On second thought, I think I'm asking for a new function, `col_vals_setdiff()`.

My current use case is data gets loaded to table(s) for each day, spanning backward for years, and I'd like to know if there are any dates are not in the table. Here's some pseudo-code, 

```
date_range <- seq(start_date, end_date, by = "day")

dates_in_table1 <- table1 %>%
  distinct(date_col_name) %>%
  collect() %>%
  pull()
  
as.Date(setdiff(date_range, dates_in_table1), origin = "1970-01-01")
```

**Comment by JakeRuss** [comment]
@rich-iannone Missed your second comment, but I think we're on the same page now, thanks!

**Comment by rich-iannone** [comment]
@JakeRuss I did a bit of work on this but the first attempt was a little hard to reason about. The perspective sort of flips with these changes so my thought is to have two new functions: `col_vals_make_set()` and `col_vals_include_subset()`. The names were something of a struggle but I hope they convey what each validation function does.

Here's the proposal (in a bit of R code that's yet to be functional). Feedback is more than welcome!

```r
library(tidyverse)
library(pointblank)

#
# `col_vals_in_set()` (EXISTS)
#
# All column values are part of a set but the distinct set of
# column values can be a subset of the defined `set`; any column
# values that are not part of the `set` result in a
# failed test unit
#
# The number of test units is `nrow(tbl)`
#

create_agent(
  tbl = tibble(x = c("a", "b", "c"))
) %>%
  col_vals_in_set(
    vars(x), set = c("a", "d", "c", "b")) %>%
  interrogate() %>%
  all_passed() # TRUE [3/3]


create_agent(
  tbl = tibble(x = c("a", "b", "c"))
) %>%
  col_vals_in_set(
    vars(x), set = c("a", "d", "b")) %>%
  interrogate() %>%
  all_passed() # FALSE (value 'c' isn't in the `set`) [2/3]


#
# `col_vals_make_set()` (NEW)
#
# All `set` values are exactly accounted for in the column values;
# any `set` values not seen at least once in the column values results
# in a failed test unit, and, any column values not part of the `set`
# contribute to a single failed test unit (lumping 'not-in-set' values)
#
# The number of test units is `length(set)` + 1
#

create_agent(
  tbl = tibble(x = c("a", "b", "c"))
) %>%
  col_vals_make_set(
    vars(x), set = c("a", "b", "c")) %>%
  interrogate() %>%
  all_passed() # TRUE

create_agent(
  tbl = tibble(x = c("a", "b", "c"))
) %>%
  col_vals_make_set(
    vars(x), set = c("c", "a", "b")) %>%
  interrogate() %>%
  all_passed() # TRUE

create_agent(
  tbl = tibble(x = c("a", "b"))
) %>%
  col_vals_make_set(
    vars(x), set = c("a", "b", "c")) %>%
  interrogate() %>%
  all_passed() # FALSE (column value 'c' is not seen) [3/4]

create_agent(
  tbl = tibble(x = c("a", "b", "c", "d"))
) %>%
  col_vals_make_set(
    vars(x), set = c("a", "b", "c")) %>%
  interrogate() %>%
  all_passed() # FALSE (column value 'd' is not part of the `set`) [3/4]


#
# `col_vals_include_subset()` (NEW)
#
# This is similar to `col_vals_make_set()` in that all `set` values
# have to be accounted for in the column values but column values not
# part of the `set` won't result in penalization
#
# The number of test units is `length(set)`
#

create_agent(
  tbl = tibble(x = c("a", "b", "c", "d", "e"))
) %>%
  col_vals_include_subset(
    vars(x), set = c("a", "b", "c")) %>%
  interrogate() %>%
  all_passed() # TRUE [3/3]

create_agent(
  tbl = tibble(x = c("a", "b", "d", "e"))
) %>%
  col_vals_include_subset(
    vars(x), set = c("a", "b", "c")) %>%
  interrogate() %>%
  all_passed() # FALSE (column value 'c' is not seen) [2/3]
```

**Comment by JakeRuss** [comment]
Hey @rich-iannone these proposed functions look great. I hadn't considered the second case of `include_subset`, but now that I see your examples, I agree some use cases may need this check. My name suggestions for `col_vals_make_set()` would be `col_vals_diff_set()/col_vals_set_diff()` or even `col_vals_complete_set()/col_vals_full_set()` but that's only because of base `setdiff()` which is the inspiration for my question. Those names might not be consistent with the rest of the package though.

**Comment by rich-iannone** [comment]
The naming has been difficult because I think, for consistency, the text after `col_vals_` should modify `col_vals` with a verb and some terminology from set theory (which I don't know a great deal about). I actually had `col_vals_complete_set()` and `col_vals_subset()` but with the latter it was too close in meaning to `col_vals_in_set()`. The `col_vals_diff_set()`/`col_vals_set_diff()` names are interesting but a little confusing since it doesn't convey the order of sets in `setdiff()` (e.g., is the set from the column values `x` or `y`).

Sorry for rambling on about this but I hope it shows where I'm coming from. Perhaps to get this done I could plow ahead with my names and still give some consideration to changing for better names before the next release.

**Comment by JakeRuss** [comment]
No need for apology. Just glad I could point out a desired validation and that you're taking up the case. Please press on!

**Comment by rich-iannone** [comment]
@JakeRuss I added the functions! Tests were added and I hope everything is good. Please test and let me know if there is some possibility for further improvement.

**Comment by JakeRuss** [comment]
@rich-iannone I've used these functions for my workflow now and they appear to have solved my use case. Many thanks. Will return here if any problems arise.

**Comment by rich-iannone** [comment]
YES! You're very welcome and I think it's a great addition to the package.
