### ISSUE TITLE
Add ability to save the `scan_data()` report

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/pointblank#279]
Scanning a table object with `scan_data()` is helpful when looking at the dataset for the first time or when inspecting it for data issues. However, the object obtained can't be saved to disk like an agent or informant with `x_write_disk()`. This would be incredibly useful especially since this object might be created rather slowly with `scan_data()`.

Thanks @kmasiello for suggesting this!

**Comment by jessecambon** [comment]
There might be a better way to do this, but this was my solution.

```r
library(here)
library(pointblank)

save_html_report <- function(df, output_filename) {
  # create report
  scan <- scan_data(
    tbl = df, 
    sections = 'OV'
  )
  
  # write html report content to file
  cat(as.character(scan), 
      file = here(output_filename)
  )
}
```
