### ISSUE TITLE
Validations that work for numeric columns should also work for Date and datetime-type columns

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/pointblank#28]
Right now date and datetime column values cannot be validated, and that’s a shame.

**Comment by rich-iannone** [comment]
This now works. Closing.

**Comment by srearl** [comment]
Hi @rich-iannone,

Thanks so very much for a wonderful package.

Sorry to resurface this old issue but I am trying to add a validation to check whether two date/POSIXct columns are identical but `pointblank` does not seem to recognize when dates are differerent. Below is a very simple MRE where a difference in the values of two columns being compared is not flagged by PB. I must just be missing something. Thanks!

```r
tibble::tibble(
  start = Sys.Date(),
  end   = Sys.Date() + lubridate::days(1)
  ) |>
pointblank::col_vals_equal(
  columns = vars("start", "end"),
  value   = "start",
  actions = pointblank::stop_on_fail()
)
```

**Comment by pachadotdev** [comment]
Hi @srearl 

I would do this

```
library(pointblank)

tibble::tibble(
  start = Sys.Date(),
  end   = Sys.Date() + lubridate::days(1)
) %>%
  create_agent(
    label = "A very *simple* example.",
    actions = action_levels(warn_at = 1)
  ) %>%
  col_vals_equal(
    columns = vars("start", "end"),
    value   = "start",
    actions = pointblank::stop_on_fail()
  ) %>%
  interrogate()
```

however, it returns an error because of "unambiguous format"
