### ISSUE TITLE
Questions: Maximum value in a column and comparing keys across tables

### ISSUE THREAD

**Issue by gofford** [rstudio/pointblank#286]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
* [ ] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

This is a great package, and a promising R-based equivalent of Great Expectations in Python. However, when building ML pipelines there are a set of transforms and tests that come up frequently, but these do not _seem_ to be available in `pointblank` at this point in time:

* **Maximum value of a column** -- Generally, I want to determine if the maximum value of a date column is yesterday. This is a breaking condition to prevent models being trained if the latest transactions haven't been received. 

* **Consistency of keys between tables** -- When applying _transforms_ to data it is often desired to ensure that all of the keys in table A are present in table B; i.e, if I train a model I want to ensure that all of the entries in my input table A have predictions in output table B. 

Are either of these operations possible within `pointblank` with the `col_vals_*` functions, perhaps in a way that I've not considered?

**Comment by rich-iannone** [comment]
Thanks for the question and for the good words! I have a set of solutions for the first scenario (a situation that is near and dear to my heart, actually):

``` r
library(tidyverse)
library(pointblank)
library(lubridate)

today <- ymd("2016-01-31")
yesterday <- today - days(1)

# Strategy A: transform the target table to get the maximum value for a column
# and make an explicit check for equality
create_agent(read_fn = ~small_table) %>%
  col_vals_equal(
    columns = vars(date), value = yesterday,
    preconditions = ~ . %>% dplyr::select(date) %>% summarize(date = max(date, na.rm = TRUE))  
  ) %>%
  interrogate()

# Strategy B: Determine whether a column of values contains a one-value subset
create_agent(read_fn = ~small_table) %>%
  col_vals_make_subset(
    columns = vars(date), set = yesterday
  ) %>%
  interrogate()
```

If you run both of these, you'll find that the single 'test unit' passes in both. Different ways of solving the same problem. One of the focus areas for this package (probably for v0.8) is to provide a set of transformer functions to safely mutate a table before applying a `col_vals_*()` validation function. Having the flexibility to mutate a table in a single step with validation functions that act dependably across backends should allow for a huge range of validations. The goal is to make it all easier and provide good documentation so that it becomes a bit more obvious.

For the second scenario, do you mean keys in the form of columns or column values (i.e., categorical values)? Either way, both can be done. Just clarify and I could provide another code example with a solution.

**Comment by rich-iannone** [comment]
Important note for strat B: it requires the development version of pointblank, obtainable by using `devtools::install_github("rich-iannone/pointblank")`. The function `col_vals_make_subset()` is not in the latest CRAN release.

**Comment by gofford** [comment]
Hey @rich-iannone that makes sense. I missed the utility of the `preconditions` flag. You Strategy A is the equivalent of what I've got in place now with `testthat`:

```
context("table: sales")
test_that("last received sales data was yesterday", {
  conn = connect_db()
  query = "
    select 
        max(to_date(orderdate, 'DD/MM/YYYY')) as date 
    from 
        stage.sales
  "
  last_received_sales_data = DBI::dbGetQuery(conn, query)$date
  yesterday = Sys.Date() - 1
  odbc::dbDisconnect(conn)
  expect_equal(last_received_sales_data, yesterday)
})
```

so good to know that it can be replicated! :)

For my second question, I am explicitly talking about column *values*. My use-case is where there are, say, 30,000 `sku` IDs in my raw data. I am training a model via a number of intermediate transforms and want to ensure that the output predictions table includes predictions for all 30k of my input `sku` IDs.  I'm curious as to how to monitor the consistency of IDs on both the input and output tables and through the intermediate steps so that we can determine if items are being dropped or removed, and where in the pipeline.

A further question on the back of the `preconditions` flag is how `pointblank` carries out the transforms and ultimately tests the data when using remote tables. If I'm using `tbl` pointing at a Redshift table, is the data pulled into R and validated in-memory (in R), or does a query (or `dbplyr` equivalent) get executed on the remote table? I'm dealing with a few hundred million rows of data in Redshift at a minimum so the former would be a blocker for adoption just from a data transfer perspective.

**Comment by rich-iannone** [comment]
Thanks for the follow up info! Here's what you can do to ensure an exact match of column values from one table source to the next (operating again on the tiny data of `small_table`):

``` r
library(tidyverse)
library(pointblank)

small_table_1 <- small_table_2 <- small_table

keys <- small_table_1 %>% dplyr::select(f) %>% dplyr::distinct() %>% dplyr::pull()

create_agent(read_fn = ~ small_table_2) %>%
  col_vals_make_set(
    columns = vars(f), set = keys
  ) %>%
  interrogate()
```

This results in 4 test units being evaluated: one for each set item plus an extra one that checks for values outside of this set. All four in this case are passing (i.e., exact set matching). The `col_vals_make_set()` function is quite new (and only available in the dev version of this package). Hope this helps and I now see the need for a basic helper function that combines `select()`, `distinct()`, and `pull()` (with a `limit` option).

To answer your question about where the validations take place, it's always in-database and only the count of passing/failing units is collected (plus data extracts--up to 5000 rows per step--all settable in `interrogate()`). My first use case in 2017 for this package was actually validating dozens of tables on Redshift (with pretty large data), so, the basic requirement from the beginning was to never collect large amounts of rows from the DB.

**Comment by gofford** [comment]
That's great @rich-iannone, thanks for the details. Definitely sounds promising and I'm keen to get stuck into testing this as a validation engine.

From your last example,  if I understand correctly, it is first necessary to define the reference set outside of the agent. Do you have a recommended/suggested way of doing this in the context of working with a database? Obvious option is to create the reference set with a query (or `dbplyr`) and then use it in the same way you define `keys` above.   I definitely agree that having a utility function for that will be good. Perhaps an even more useful function would be one where it is possible to provide a reference `tbl` against which we compare the set automatically without having to manually define the `keys`.

Great package, and I'm sure I'll have more questions and ideas in future. Great work. Pending response to above I'm happy to close this thread out.

**Comment by rich-iannone** [comment]
I've recently added in some functions that make DB access a little nicer (`db_tbl()`, and `tbl_store()`). While I don't have `small_table` in a DB we can use the similar-in-behavior `file_tbl()` to pull the same data (again, pretend it's different) from a repo and make the validation self-contained:

``` r
agent <- 
  create_agent(read_fn = ~ pointblank::small_table) %>%
  col_vals_make_set(
    columns = vars(f), 
    set = file_tbl(
      from_github(
        file = "small_table.rda",
        repo = "rich-iannone/pointblank",
        subdir = "data")
    ) %>% 
      dplyr::select(f) %>% dplyr::distinct() %>% dplyr::pull()
  ) %>%
  interrogate()
```

What I currently don't like about this is that we can't (yet) provide the `file_tbl()` call as a RHS formula expression. The reason I don't like it is that the agent won't preserve the expression in it's YAML representation (useful if you want to reuse the agent from disk with `yaml_agent_interrogate()` and always re-eval since the data sources will change).

I think utility functions (for many common operations like this) and stored expressions will be areas of development and I'd appreciate your input every now then on what could make the API better in real-world use cases!

**Comment by gofford** [comment]
For what it's worth, your Strategy A above worked but _only_ if the `preconditions` were `collect`ed. Without that the test fails. 

Going to close this thread and move further questions to Discussions, which I only just found. Thanks @rich-iannone!
