### ISSUE TITLE
Template script produces error when using RStudio 'knit' button

### ISSUE THREAD

**Issue by DHPatch** [rstudio/pointblank#291]
First let me say this is the first time I have submitted an Issue on Github, so my apologies for any mistakes/missing important information. These mistakes are not out of laziness, but ignorance. I am raising this issue because I think this package could be _really_ useful in my workplace, and has the potential to make many peoples lives better, I do not doubt the package authors contribution and hard work. If you let me know if I am missing any necessary information, I will try to add what I can.

## Prework

* [ x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
* [ -] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [NA ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ NA] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ NA] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ NA] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description  

Trying to knit template pointblank script using the "knit" button in RStudio produces an error:
  
> Error in .transformer(expr, env) : object '=html' not found
> Calls: \<Anonymous> ... pb_glue_data -> \<Anonymous> -> \<Anonymous> -> .transformer
> Execution halted
  

Using
> rmarkdown::render("C:/path/to/file/pointblank test.Rmd")  

A html output is produced, but just an ordinary html file (no 'X validations failed' buttons, cannot hide chunk output).

The individual code chunks seem to output , it is only when using the knit button that the error is thrown.
I have had this work a couple of months ago, I believe with pointblank v0.6, so possible breaking change in dependency?

The code in this package is beyond my current level of understnading, 

## Reproducible example

Template pointblank file

* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Expected result

Template Rmd rendered into a html file.

## Session info

I have seen the same error on my work laptop and my personal laptop.
Session info from my personal laptop below:

I am using RStudio version: 1.4.1103

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pointblank_0.6.0

loaded via a namespace (and not attached):
 [1] pillar_1.5.0      bslib_0.2.4       compiler_4.0.3    jquerylib_0.1.3   base64enc_0.1-3  
 [6] tools_4.0.3       digest_0.6.27     checkmate_2.0.0   gtable_0.3.0      jsonlite_1.7.2   
[11] evaluate_0.14     lifecycle_1.0.0   tibble_3.0.6      pkgconfig_2.0.3   rlang_0.4.10     
[16] DBI_1.1.1         cli_2.3.1         rstudioapi_0.13   commonmark_1.7    yaml_2.2.1       
[21] xfun_0.21         stringr_1.4.0     dplyr_1.0.4       knitr_1.31        generics_0.1.0   
[26] vctrs_0.3.6       sass_0.3.1        grid_4.0.3        tidyselect_1.1.0  glue_1.4.2       
[31] R6_2.5.0          fansi_0.4.2       rmarkdown_2.7     blastula_0.3.2    purrr_0.3.4      
[36] ggplot2_3.3.3     magrittr_2.0.1    backports_1.2.1   scales_1.1.1      ellipsis_0.3.1   
[41] htmltools_0.5.1.1 assertthat_0.2.1  gt_0.2.2          colorspace_2.0-0  utf8_1.1.4       
[46] tinytex_0.29      stringi_1.5.3     munsell_0.5.0     crayon_1.4.1  
End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(si = TRUE)`) and include the output.

**Comment by rich-iannone** [comment]
Thanks for reporting this! 

About 1-2 months back I did notice general failures with this very thing and it was because of what you suspected ('possible breaking change in dependency'). The issue was fixed but this occurred after the v0.6 release. Just to make sure these aren't *newer* breaking changes (or something I missed in testing) could you install the dev version of pointblank with `devtools::install_github("rich-iannone/pointblank")`, try once again, and report back?

The release of v0.7 is pretty close now (pending documentation enhancements) so I'm hoping this will no longer be a problem for the CRAN version (if indeed this issue was something already fixed in dev).

**Comment by DHPatch** [comment]
Hi, you are correct - knitting the template file using the dev version works, these aren't newer breaking changes (phew).

I should have thought to try the dev version, hopefully I will remember to do so in future.

Thanks very much for your help.
