### ISSUE TITLE
write_testthat_file() errors if no interrogation performed

### ISSUE THREAD

**Issue by Aariq** [rstudio/pointblank#298]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Not sure if this is a bug or just a need for a more descriptive error message. If an agent is created, but not run through `interrogate()`, then `write_testthat_file()` errors with an uninformative error message.

## Reproducible example
``` r
library(pointblank)
al <- 
  action_levels(
    warn_at = 0.10,
    stop_at = 0.25,
    notify_at = 0.35
  )

agent <- 
  create_agent(
    read_fn = ~ small_table,
    label = "An example.",
    actions = al
  ) %>%
  col_exists(vars(date, date_time)) %>%
  col_vals_gt(vars(d), value = 100)

write_testthat_file(agent, path = tempdir())
```

    #> Error in if (step_inactive[i]) {: missing value where TRUE/FALSE needed

<sup>Created on 2021-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

``` r
devtools::session_info()
```

    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.7      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2021-03-12                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version date       lib source        
    #>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
    #>  blastula      0.3.2   2020-05-19 [1] CRAN (R 4.0.2)
    #>  callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.2)
    #>  cli           2.3.1   2021-02-23 [1] CRAN (R 4.0.2)
    #>  colorspace    2.0-0   2020-11-11 [1] CRAN (R 4.0.2)
    #>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.2)
    #>  DBI           1.1.0   2019-12-15 [1] CRAN (R 4.0.0)
    #>  desc          1.3.0   2021-03-05 [1] CRAN (R 4.0.2)
    #>  devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.2)
    #>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.2)
    #>  dplyr         1.0.3   2021-01-15 [1] CRAN (R 4.0.2)
    #>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
    #>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
    #>  fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.2)
    #>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
    #>  generics      0.1.0   2020-10-31 [1] CRAN (R 4.0.2)
    #>  ggplot2       3.3.3   2020-12-30 [1] CRAN (R 4.0.2)
    #>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
    #>  gt            0.2.2   2020-08-05 [1] CRAN (R 4.0.2)
    #>  gtable        0.3.0   2019-03-25 [1] CRAN (R 4.0.0)
    #>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.2)
    #>  htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.0)
    #>  knitr         1.30    2020-09-22 [1] CRAN (R 4.0.2)
    #>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.2)
    #>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
    #>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
    #>  munsell       0.5.0   2018-06-12 [1] CRAN (R 4.0.0)
    #>  pillar        1.5.1   2021-03-05 [1] CRAN (R 4.0.2)
    #>  pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.2)
    #>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
    #>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
    #>  pointblank  * 0.7.0   2021-03-09 [1] CRAN (R 4.0.2)
    #>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
    #>  processx      3.4.5   2020-11-30 [1] CRAN (R 4.0.2)
    #>  ps            1.5.0   2020-12-05 [1] CRAN (R 4.0.2)
    #>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
    #>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.2)
    #>  remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.0)
    #>  rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.2)
    #>  rmarkdown     2.6     2020-12-14 [1] CRAN (R 4.0.2)
    #>  rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.2)
    #>  scales        1.1.1   2020-05-11 [1] CRAN (R 4.0.0)
    #>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
    #>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
    #>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
    #>  testthat      3.0.1   2020-12-17 [1] CRAN (R 4.0.2)
    #>  tibble        3.1.0   2021-02-25 [1] CRAN (R 4.0.2)
    #>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
    #>  usethis       2.0.1   2021-02-10 [1] CRAN (R 4.0.2)
    #>  utf8          1.1.4   2018-05-24 [1] CRAN (R 4.0.0)
    #>  vctrs         0.3.6   2020-12-17 [1] CRAN (R 4.0.2)
    #>  withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.2)
    #>  xfun          0.20    2021-01-06 [1] CRAN (R 4.0.2)
    #>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
    #> 
    #> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

------------------------------------------------------------------------

title: reprex\_reprex.R
author: scottericr
date: ‘2021-03-12’

------------------------------------------------------------------------

## Expected result

I would expect an error that says something like "agent must be output of interrogate()".  Or possibly some other non-error behavior.

**Comment by Aariq** [comment]
It seems like there are other conditions that result in this same error---adding `interrogate()` didn't fix my particular situation and I'm still getting the same error message.

**Comment by rich-iannone** [comment]
Thanks for catching this. I actually wanted the interrogation to be completely optional/independent of creating a testthat file. Will fix this soon!

**Comment by Aariq** [comment]
Yeah, it seems like the other issue has to do with `step_inactive` not being the same length as `seq_along(agent_exprs_raw)`, so that for-loop fails

**Comment by rich-iannone** [comment]
Oh on closer inspection it does looks like another code issue. Thanks again for the detailed issue.

**Comment by rich-iannone** [comment]
I just made the fixes in master. Now works on my system and CI passes. Would you be able to install from GitHub and verify that it works for you? If so, feel free to close the issue.

**Comment by Aariq** [comment]
Works now!  One of the tests got created with a `label` argument, which errors saying it is unused, but that's a different issue.

**Comment by rich-iannone** [comment]
@Aariq Thanks! If you can, I would definitely appreciate if you could file a new Issue that states that validation steps with `label` values cause errors for `write_testthat_file()`.

**Comment by Aariq** [comment]
I'll file one if I get a chance.  It also didn't handle preconditions well when code spanned multiple lines (each line of a dplyr pipeline got split into a different test with broken test function names).

**Comment by rich-iannone** [comment]
Yeesh! Okay, there's a bit of work to do here. Thanks!
