### ISSUE TITLE
Support checks for repeated measures / panel data

### ISSUE THREAD

**Issue by emilyriederer** [rstudio/pointblank#300]
## Prework

- [x] Read and abide by **pointblank**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rich-iannone/pointblank/issues) (both open and closed).

## Proposal

I'm opening this issue per our discussion (#297)

When working with panel data, I often find it is helpful to do checks _within_ each observation. For example, if one is analyzing data for a set of customers, it could be useful to specify checks within observations, such as:

- Uniqueness of a column within but not between groups (e.g. YEAR is unique given COUNTRY but different COUNTRYs can have the same YEAR)
- Values increasing within each group (but can decrease between)
- The values of some column within each group contain all values of a prespecified set, so check can fail in all values exist in column but do not exist for each group

Current workarounds include: 

- running `interrogate()` with a nest-map paradigm; however, this seems unnecessarily inefficient and would fragment the out-of-the-box reporting in an awkward way
- sometimes using `preconditions` to create mock columns that can "trick" the checks into working (e.g. hacks like seeing if `account_number * 1000 + other_thing_i_want_to_be_unique_by_group` is unique); however, this doesn't work for all checks (e.g. the "set" checks)

In the discussion thread, we discuss potential solutions such as:

- an optional `groups` argument in the checks
- using `dplyr`-esque check for `groups_vars()` / `groups` aesthetic

Caveats to think about include:

- It's also interesting to think about how this changes reporting. In cases where users are looking for errors within group, I'm not sure if the more useful "success metric" would be the number of "bad" rows or the number of _observations_ that have any bad rows 
- Our discussion revealed that there are multiple different types of "groupwise" issues (I mostly describe the first one above. All might be useful but unfortunately probably vary substantially in implementation.)
  + Apply same checks _within_ groups
  + Apply different checks (or parameters for checks) dependent on groups

**Comment by rich-iannone** [comment]
Thanks for opening this issue!

Thinking about it *even more*, having both a check for grouping vars in the target table **and** a `groups` argument makes a lot of sense. In terms of priority order, a non-NULL `groups` argument would override grouping vars in the target table. The flexibility of having both options means you can have a mix of full table and within group validation steps (without having to mess with `preconditions`, just add a column or two to `groups`).

**Comment by rich-iannone** [comment]
From the discussion, you mentioned: 'I wonder if for non-dplyr data structures you could simply add a helper function that adds a similar attribute to other types of objects in a non-disruptive way?'.

Yep, I think that would be useful. There's already a few utility-helper functions in the package so it wouldn't be out of place.

If making a `groups` arg, I also think we can allow some helper functions to work there as well. Maybe even pull in some tidyselect ones (would only reasonably work for one grouping var). We may want to target only certain categories in the group (e.g., omitting the `NA`/`NULL` group if it exists) so our own helpers would be needed to specify these sorts of things.

**Comment by emilyriederer** [comment]
🥳 @rich-iannone -- the syntax example in the PR looks fantastic! I can't wait to try this out. Thank you!

**Comment by rich-iannone** [comment]
Thanks @emilyriederer ! Let me know if there’s anything I may have missed.
