### ISSUE TITLE
Return failure rows in CSV but have `all_passed()` return TRUE

### ISSUE THREAD

**Issue by tylerlittlefield** [rstudio/pointblank#342]
I have the following system in place:
1. I run quality reports daily using `pointblank`
2. For each report, I call `all_passed()` on the agent 
3. If all passes, I store in the report in a specific folder on our server
4. If something fails, I copy the report to the `failure` directory on our server

However, there are some checks that have failures and I want those checks to be ignored when calling `all_passed()`. Additionally, I still want this check to exist so that there is a record of the rows having this quality issue. These are basically errors in the data that for various reasons, will never be fixed but I nonetheless want people to be aware of it.

**Comment by rich-iannone** [comment]
Thanks for filing this issue, it's a good one. An idea to make `all_passed()` a bit more powerful would be to add the `i` argument that `get_data_extracts()` (https://rich-iannone.github.io/pointblank/reference/get_data_extracts.html) and `get_agent_x_list()`(https://rich-iannone.github.io/pointblank/reference/get_agent_x_list.html) both have.

By default, as in the other functions that have it, `i` would be set to `NULL`, providing no change in behavior (it would consider all steps). Should you supply an integer vector to `i` then the `all_passed()` function would only check if all those specified steps passed.

Let me know if this sounds like a good plan for improving that function!

**Comment by tylerlittlefield** [comment]
I see, thanks for sharing! This looks like a good solution to me. I may use `get_data_extracts()` for my particular use case :)
