### ISSUE TITLE
Have `all_passed()` return FALSE when there are evaluation errors?

### ISSUE THREAD

**Issue by tylerlittlefield** [rstudio/pointblank#343]
I often want `all_passed()` to return FALSE if there is anything other than `TRUE` in the result, e.g. `agent$validation_set$all_passed`. This means, NA would be interpreted as a failure and from what I have gathered, this happens when there is an evaluation error. I can see benefits to both behaviors, current behavior and the one I am suggesting. Maybe it would be worth it to add a parameter like `na_rm` or `evaluation_error` so that users can fine tune what `all_passed()` means. Example below:

```r
library(pointblank)

out <- small_table %>% 
  create_agent(actions = action_levels(
    warn_at = 0.2,
    stop_at = 0.8,
    notify_at = 0.5
  )) %>%
  col_vals_not_null(vars("z")) %>%  # <-- evaluation error
  col_exists("f") %>% 
  interrogate()

# returns NA but I would prefer it returns FALSE
all_passed(out)

# vector of passed/failed
out$validation_set$all_passed
```

**Comment by rich-iannone** [comment]
I agree this is not flexible in its current form and an `na_rm` argument (maybe with a default of `FALSE`) would be the way to go here. Thanks!
