### ISSUE TITLE
Beyond data frames?

### ISSUE THREAD

**Issue by iqis** [rstudio/pointblank#351]
Hi, authors! 

I came here via Emily's [post](https://emilyriederer.netlify.app/post/data-valid-lightweight/) This seems like a very elaborate and carefully designed framework. Good job!

Not all data lives in a data frame. It may be valuable to make it convenient to create custom expectations to allow the user to take advantage of the very nice reporting utilities.  For example, I may want to check how many of my API returns are valid, or what portion of my logs match a certain regex pattern. 

Is it within scope to generalize and extend the domain of this package to any R objects?

**Comment by rich-iannone** [comment]
Thanks for the great suggestion! I have this some thought and, yeah, it seems like a great idea to have a function to help create custom expectations. 

My guess is that what’s needed is an argument to accept a function (that performs the validation) and what’s needed from the fn’s return value is a data frame with the last column being logical (it’ll have the eval’d results, either TRUE, FALSE, or NA). 

This should be a great addition so I’m glad you filed this issue!
