### ISSUE TITLE
`col_vals_XXX` fails on SQL Server connection

### ISSUE THREAD

**Issue by LDalby** [rstudio/pointblank#352]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Connecting to one of our databases and trying to run `interrrogate()` throws an error when using the `col_vals_XXX` family of functions. So in example below, the `col_is_date()` runs fine, but `col_vals_between()` does not. I can't really figure out why?
If I collect the needed columns using `dplyr::collect()` and run the exact same chunk everything works fine. Same goes for a similar interrogation on the `small_table_duckdb`.

NOTE: I'm aware that the example is a pseudo reprex - I included it here, so you can see what I did. If there is anyway I can improve the example code, please just let me know!

## Reproducible example

``` r
library(pointblank)
small_table_duckdb <- 
  db_tbl(
    table = small_table,
    dbname = ":memory:",
    dbtype = "duckdb"
  )

stdb_agent <- create_agent(read_fn = ~ small_table_duckdb) |> 
  col_is_character(vars(b)) |>
  col_vals_between(vars(a), left = 0, right = 1000000) |> 
  interrogate()


con <- DBI::dbConnect(odbc::odbc(),
                      driver   = "ODBC Driver 17 for SQL Server",
                      server   = <OUR SERVER>,
                      database = <OUR DATABASE>,
                      uid      = <THE UID>,
                      pwd      = <THE PWD>)


kemi <- dplyr::tbl(con, dbplyr::in_schema("data", "kemi"))

kemi_agent <- create_agent(read_fn = ~ kemi) |>
  col_is_date(vars(dato)) |>
  col_vals_between(
    columns = vars(jord_C),
    left = 0.1,
    right = 30,
    na_pass = TRUE
  ) |>
  interrogate()
```

    #> Error: nanodbc/nanodbc.cpp:1655: 00000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near ')'.  [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'jord_C'.  [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. 
    #> <SQL> 'SELECT "n"
    #> FROM (SELECT COUNT(*) AS "n"
    #> FROM (SELECT "progId", "aktId", "dato", "sted", "avneknippe_5m", "befaestet_areal_15m", "biomasse_N", "biomasse_torvaegt", "bladbille_5m", "blottet_mineraljord_5m", "bredbladede_urter_5m", "dvaergbuske_5m", "enebaer_5m", "fornelag_tykkelse_1", "fornelag_tykkelse_2", "fornelag_tykkelse_3", "fornelag_tykkelse_4", "graaris_5m", "graesser_5m", "halvgraesser_siv_og_frytle_5m", "havtorn_5m", "hegnet_areal_15m", "holjer_5m", "hulheder_15m", "humuslag_tykkelse_1", "humuslag_tykkelse_2", "humuslag_tykkelse_3", "humuslag_tykkelse_4", "jord_C", "jord_C_under_detektionsgraensen", "jord_N", "jord_N_under_detektionsgraensen", "jord_basemaetning", "jord_fosfortal", "jord_fosfortal_under_detektionsgraensen", "jord_ph", "jordprove_torvaegt", "klokkelyng_5m", "lichener_5m", "lysforhold_1", "lysforhold_2", "lysforhold_3", "lysforhold_4", "morlagstykkelse_1", "morlagstykkelse_2", "morlagstykkelse_3", "morlagstykkelse_4", "mosser_5m", "naturtype", "plante_N", "plante_N_art", "plante_P", "raad_15m", "trunter_15m", "vadegraes_5m", "vand_NH4", "vand_NH4_N_under_detektionsgraensen", "vand_NO3", "vand_NO3_N_under_detektionsgraensen", "vand_PO4", "vand_PO4_P_under_detektionsgraensen", "vand_ledningsevne", "vand_ph", "vandflade_5m", "vandstand_pejling", "vedplanter_over_1m", "vedplanter_samlet", "vedplanter_under_1m", "vegetationshojde_1", "vegetationshojde_2", "vegetationshojde_3", "vegetationshojde_4", CASE
    #> WHEN ("jord_C" >= 0.1 AND "jord_C" <= 30.0) THEN (TRUE)
    #> WHEN ("jord_C" < 0.1 OR "jord_C" > 30.0) THEN (FALSE)
    #> WHEN ((("jord_C") IS NULL) AND TRUE) THEN (TRUE)
    #> WHEN ((("jord_C") IS NULL) AND TRUE = FALSE) THEN (FALSE)
    #> END AS "pb_is_good_"
    #> FROM "data"."kemi") "q01") "q02"'

``` r
kemi |> 
  dplyr::select(dato, jord_C) |> 
  dplyr::collect() -> kemi_local

kemi_agent <- create_agent(read_fn = ~ kemi_local) |>
  col_is_date(vars(dato)) |>
  col_vals_between(
    columns = vars(jord_C),
    left = 0.1,
    right = 30,
    na_pass = TRUE
  ) |>
  interrogate()
```

<sup>Created on 2021-09-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
```

    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.1.1 (2021-08-10)
    #>  os       Ubuntu 20.04.3 LTS          
    #>  system   x86_64, linux-gnu           
    #>  ui       X11                         
    #>  language en_US:en                    
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       Europe/Copenhagen           
    #>  date     2021-09-08                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version    date       lib
    #>  assertthat    0.2.1      2019-03-21 [1]
    #>  backports     1.2.1      2020-12-09 [1]
    #>  bit           4.0.4      2020-08-04 [1]
    #>  bit64         4.0.5      2020-08-30 [1]
    #>  blastula      0.3.2      2020-05-19 [1]
    #>  blob          1.2.2      2021-07-23 [1]
    #>  cli           3.0.1      2021-07-17 [3]
    #>  crayon        1.4.1      2021-02-08 [3]
    #>  DBI           1.1.1      2021-01-15 [1]
    #>  dbplyr        2.1.1      2021-04-06 [1]
    #>  digest        0.6.27     2020-10-24 [3]
    #>  dplyr         1.0.7      2021-06-18 [1]
    #>  duckdb        0.2.9      2021-09-06 [1]
    #>  ellipsis      0.3.2      2021-04-29 [3]
    #>  evaluate      0.14       2019-05-28 [3]
    #>  fansi         0.5.0      2021-05-25 [1]
    #>  fastmap       1.1.0      2021-01-25 [3]
    #>  fs            1.5.0      2020-07-31 [1]
    #>  generics      0.1.0      2020-10-31 [1]
    #>  glue          1.4.2      2020-08-27 [3]
    #>  highr         0.9        2021-04-16 [3]
    #>  hms           1.1.0      2021-05-17 [1]
    #>  htmltools     0.5.2      2021-08-25 [1]
    #>  knitr         1.33       2021-04-24 [3]
    #>  lifecycle     1.0.0      2021-02-15 [3]
    #>  magrittr      2.0.1      2020-11-17 [3]
    #>  odbc          1.3.2      2021-04-03 [1]
    #>  pillar        1.6.2      2021-07-29 [3]
    #>  pkgconfig     2.0.3      2019-09-22 [3]
    #>  pointblank  * 0.8.0.9000 2021-09-08 [1]
    #>  purrr         0.3.4      2020-04-17 [3]
    #>  R6            2.5.1      2021-08-19 [3]
    #>  Rcpp          1.0.7      2021-07-07 [1]
    #>  reprex        2.0.1      2021-08-05 [1]
    #>  rlang         0.4.11     2021-04-30 [3]
    #>  rmarkdown     2.10       2021-08-06 [1]
    #>  rstudioapi    0.13       2020-11-12 [3]
    #>  sessioninfo   1.1.1      2018-11-05 [3]
    #>  stringi       1.7.4      2021-08-25 [1]
    #>  stringr       1.4.0      2019-02-10 [3]
    #>  styler        1.5.1      2021-07-13 [1]
    #>  tibble        3.1.4      2021-08-25 [1]
    #>  tidyselect    1.1.1      2021-04-30 [1]
    #>  utf8          1.2.2      2021-07-24 [3]
    #>  vctrs         0.3.8      2021-04-29 [3]
    #>  withr         2.4.2      2021-04-18 [3]
    #>  xfun          0.25       2021-08-06 [1]
    #>  yaml          2.2.1      2020-02-01 [3]
    #>  source                                  
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.1)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.1)                          
    #>  CRAN (R 4.0.5)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.5)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.1)                          
    #>  CRAN (R 4.0.5)                          
    #>  CRAN (R 4.0.4)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  Github (rich-iannone/pointblank@9396547)
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.1.1)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.0.5)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.1.1)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.1)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.0.5)                          
    #>  CRAN (R 4.0.5)                          
    #>  CRAN (R 4.1.0)                          
    #>  CRAN (R 4.0.0)                          
    #> 
    #> [1] /home/au206907/R/x86_64-pc-linux-gnu-library/4.1
    #> [2] /usr/local/lib/R/site-library
    #> [3] /usr/lib/R/site-library
    #> [4] /usr/lib/R/library

</details>

## Expected result

I expected the interrogation to be carried out just like for the other cases.

**Comment by rich-iannone** [comment]
Sorry to hear that `mssql` tables are not working well at all with (presumably) most of the functions. We can definitely fix this, and it’s something we’ve been meaning to do for some time now. 

We’ll make a push to fix and test all functions with a live `mssql` DB soon. Just in case it’s important, what version of SQL Server are you using?

**Comment by LDalby** [comment]
Sounds good! 

We currently running this:
`
Microsoft SQL Server 2017 (RTM-CU22-GDR) (KB4583457) - 14.0.3370.1 (X64)   Nov  6 2020 18:19:52   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
`

**Comment by pachadotdev** [comment]
@rich-iannone Hi, I translated this to an actual failing query with nycflights13 on SQL Server 2017

```
library(pointblank)
library(odbc)

# see https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

con <- dbConnect(
  odbc(),
  Driver = "ODBC Driver 17 for SQL Server",
  UID = Sys.getenv("dbedu_usr"),
  PWD = Sys.getenv("dbedu_pwd"),
  Database = "nycflights13",
  Server = "databases.pacha.dev"
)

planes <- dplyr::tbl(con, "planes")

al <-  action_levels(warn_at = 0.02, stop_at = 0.05, notify_at = 0.10)

planes_agent <- create_agent(read_fn = ~ planes) %>%
  col_is_character(vars(manufacturer)) %>%
  col_vals_between(
    columns = vars(year),
    left = 1900L,
    right = 2021L,
    na_pass = TRUE
  ) %>%
  interrogate()

# problematic query

dbGetQuery(
  con,
  '
  SELECT "n"
FROM (SELECT COUNT(*) AS "n"
FROM (SELECT "tailnum", "year", "type", "manufacturer", "model", "engines", "seats", "speed", "engine", CASE
WHEN ("year" >= 1900 AND "year" <= 2021) THEN (TRUE)
WHEN ("year" < 1900 OR "year" > 2021) THEN (FALSE)
WHEN ((("year") IS NULL) AND TRUE) THEN (TRUE)
WHEN ((("year") IS NULL) AND TRUE = FALSE) THEN (FALSE)
END AS "pb_is_good_"
FROM "planes") "q01") "q02"
  '
)
```

**Comment by rich-iannone** [comment]
@pachadotdev Thank you so much! I’ll start looking at this and we should be able to get a better query generated in no time. Are you okay with DMing me the credentials for your DB?

**Comment by pachadotdev** [comment]
sorry the slow replied, DMed!

**Comment by pachadotdev** [comment]
@rich-iannone  I've sent you the credentials

here's a spoiler of what NOT to do: at some point I identified https://github.com/rich-iannone/pointblank/issues/144 and solved it in https://github.com/rich-iannone/pointblank/issues/146, the problem of fixing "pb_is_good" by replacing T/F by 1/0 for SQL Server, is that it adds a full replacement in the full table, therefore making everything slow, and this is why #146 was partially reverted

i.e. this was a good idea to be applied only for MSQL, but it has to be applied in a different way https://github.com/rich-iannone/pointblank/pull/146/files#diff-1521fa5bcc19c4eb178dc0649aa5975dac6f4fd482f4c4668b66d1c68c2aa202R1147-R1161

**Comment by pachadotdev** [comment]
the problematic line is https://github.com/rich-iannone/pointblank/blob/main/R/interrogate.R#L613

I am trying this chunk-wise code to isolate the problem
```
library(pointblank)
library(odbc)

# see https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

con <- dbConnect(
  odbc(),
  Driver = "ODBC Driver 17 for SQL Server",
  UID = Sys.getenv("dbedu_usr"),
  PWD = Sys.getenv("dbedu_pwd"),
  Database = "nycflights13",
  Server = "databases.pacha.dev"
)

planes <- dplyr::tbl(con, "planes")

al <-  action_levels(warn_at = 0.02, stop_at = 0.05, notify_at = 0.10)

planes_agent <- create_agent(planes)

planes_agent <- planes_agent %>% 
  col_is_character(vars(manufacturer))

planes_agent <- planes_agent %>% 
  col_vals_between(
    columns = vars(year),
    left = 1900L,
    right = 2021L,
    na_pass = TRUE
  )

planes_agent <- planes_agent %>% 
  interrogate()

dbDisconnect(con)
````

after sourcing each function and running the code line by line, the aforementioned tbl_checked returns
```
> tbl_checked
$value
Error: nanodbc/nanodbc.cpp:1655: 00000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near ')'.  [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'year'.  [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. 
<SQL> 'SELECT TOP 11 "tailnum", "year", "type", "manufacturer", "model", "engines", "seats", "speed", "engine", CASE
WHEN ("year" >= 1900 AND "year" <= 2021) THEN (TRUE)
WHEN ("year" < 1900 OR "year" > 2021) THEN (FALSE)
WHEN ((("year") IS NULL) AND TRUE) THEN (TRUE)
WHEN ((("year") IS NULL) AND TRUE = FALSE) THEN (FALSE)
END AS "pb_is_good_"
FROM "planes"'
```

for i=2


above in the code, in https://github.com/rich-iannone/pointblank/blob/main/R/interrogate.R#L235 the tbl_check object is created but the query is wrong, therefore tbl_checked$value is the problem

the function that creates the query is https://github.com/rich-iannone/pointblank/blob/main/R/interrogate.R#L869, which depends on https://github.com/rich-iannone/pointblank/blob/main/R/interrogate.R#L1100 and which in turn depends on https://github.com/rich-iannone/pointblank/blob/main/R/interrogate.R#L1192

**Comment by pachadotdev** [comment]
@rich-iannone I created a start of solution here
the problem is that it fixes the error in this PR https://github.com/rich-iannone/pointblank/pull/384, it introduces a new error
```
── Interrogation Started - there are 2 steps ────────────────────────────────────────────────────────────────────────────────────────
✓ Step 1: OK.
The input is Microsoft SQL Server, we need to collect the data and transform
 Error in UseMethod("filter") : 
  no applicable method for 'filter' applied to an object of class "table_eval" 
```

**Comment by pachadotdev** [comment]
solution (joke not so joke): offer consultancy with discount to help people to move to PostgreSQL (I also don't like MySQL/MariaDB)

**Comment by pachadotdev** [comment]
@LDalby hi, just a follow up, did you check that you can actually run your code now?
I installed pointblank again (i.e. `devtools::install_github("rich-iannone/pointblank")` and the code I added in previous posts now works

**Comment by LDalby** [comment]
Hi @pachadotdev and thanks for reaching out. 
I have seen the recent activity here, but I have not yet had the chance to test if my code runs with the dev version. 
I hope I will get a chance to do that next week.

**Comment by LDalby** [comment]
Finally got around to trying this out and yes - my code now runs! 🥳 
Thanks for the effort @rich-iannone & @pachadotdev
