### ISSUE TITLE
support data label in `scan_data`

### ISSUE THREAD

**Issue by elong0527** [rstudio/pointblank#357]
## Prework

- [ ] Read and abide by **pointblank**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
- [ ] Search for duplicates among the [existing issues](https://github.com/rich-iannone/pointblank/issues) (both open and closed).

## Proposal

It could be helpful if `scan_data` can display variable label if it is available.

For example, ADaM dataset typically contain variable label.

https://github.com/RConsortium/submissions-pilot1/tree/main/adam
 
```
> attributes(adsl$SITEID)
$label
[1] "Study Site Identifier"
```

**Comment by rich-iannone** [comment]
This is a great feature request and I really want to support this initiative. I will get this working pretty soon!

One question, do labeled variables in R always standardize to the `label` attribute? I'm going to assume 'yes' for now but if you have additional insight on this (and maybe other attributes that should be rendered) please let me know.

**Comment by elong0527** [comment]
Thanks! I assume tibble use this convention and the label attributes is supported by the Rstudio data preview. (i.e. using 'View')

**Comment by rich-iannone** [comment]
This is now in `main`. Column labels have been added to the table scan (if available).

Here is an excerpt of a report using the following code:

```r

library(pointblank)
library(haven)

adadas <- read_xpt(file = "https://github.com/RConsortium/submissions-pilot1/blob/main/adam/adadas.xpt?raw=true")

scan_data(adadas, sections = "OVS")
```

<img width="894" alt="table_scan_labels" src="https://user-images.githubusercontent.com/5612024/137249239-5e6b8195-bdb6-4799-9ba0-48bcb6df0e87.png">

Will close the issue now but reopen of course if you find any problems with this!
