### ISSUE TITLE
Loading `pointblank` breaks `knitr::knit_child()` workflow.

### ISSUE THREAD

**Issue by Aariq** [rstudio/pointblank#369]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I've been trying to figure out a good way to apply the same agent to a list of data frames with similar structure and output a markdown report with multiple interrogations.  I came across a workflow using `knitr::knit_child()`, but discovered some unexpected behavior with `pointblank`. Just having `pointblank` loaded seems to break this workflow.

## Reproducible Example

This works:

``` r
res <- lapply(list(mtcars, iris),
              function(x) {
                knitr::knit_child(text = c(
                  '## dimension = `r dim(x)`',
                  '',
                  '```{r}',
                  'head(x)',
                  '```',
                  ''
                ), envir = environment(), quiet = TRUE)
              })
cat(unlist(res), sep = '\n')
#> 
#> ## dimension = 32, 11
#> 
#> 
#> ```r
#> head(x)
#> #>                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> #> Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> #> Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> #> Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> #> Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> #> Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> #> Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
#> ```
#> 
#> 
#> ## dimension = 150, 5
#> 
#> 
#> ```r
#> head(x)
#> #>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> #> 1          5.1         3.5          1.4         0.2  setosa
#> #> 2          4.9         3.0          1.4         0.2  setosa
#> #> 3          4.7         3.2          1.3         0.2  setosa
#> #> 4          4.6         3.1          1.5         0.2  setosa
#> #> 5          5.0         3.6          1.4         0.2  setosa
#> #> 6          5.4         3.9          1.7         0.4  setosa
#> ```
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

But if `pointblank` is loaded first I get this:

``` r
library(pointblank)
res <- lapply(list(mtcars, iris),
              function(x) {
                knitr::knit_child(text = c(
                  '## dimension = `r dim(x)`',
                  '',
                  '```{r}',
                  'head(x)',
                  '```',
                  ''
                ), envir = environment(), quiet = TRUE)
              })
cat(unlist(res), sep = '\n')
```

    #> 
    #> NA
    #> ---
    #> 
    #> NA
    #> 
    #> NA
    #> ---
    #> 
    #> NA

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
```

    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS  10.16                
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2021-11-29                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version date       lib source        
    #>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
    #>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.0.2)
    #>  blastula      0.3.2   2020-05-19 [1] CRAN (R 4.0.2)
    #>  cli           3.1.0   2021-10-27 [1] CRAN (R 4.0.2)
    #>  crayon        1.4.2   2021-10-29 [1] CRAN (R 4.0.2)
    #>  DBI           1.1.1   2021-01-15 [1] CRAN (R 4.0.2)
    #>  digest        0.6.28  2021-09-23 [1] CRAN (R 4.0.2)
    #>  dplyr         1.0.7   2021-06-18 [1] CRAN (R 4.0.2)
    #>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.0.2)
    #>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
    #>  fansi         0.5.0   2021-05-25 [1] CRAN (R 4.0.2)
    #>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.2)
    #>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
    #>  generics      0.1.1   2021-10-25 [1] CRAN (R 4.0.2)
    #>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
    #>  highr         0.9     2021-04-16 [1] CRAN (R 4.0.2)
    #>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.0.2)
    #>  knitr         1.36    2021-09-29 [1] CRAN (R 4.0.2)
    #>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.0.2)
    #>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
    #>  pillar        1.6.4   2021-10-18 [1] CRAN (R 4.0.2)
    #>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
    #>  pointblank  * 0.9.0   2021-10-28 [1] CRAN (R 4.0.2)
    #>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
    #>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.0.2)
    #>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.0.2)
    #>  rlang         0.4.12  2021-10-18 [1] CRAN (R 4.0.2)
    #>  rmarkdown     2.10    2021-08-06 [1] CRAN (R 4.0.2)
    #>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.2)
    #>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
    #>  stringi       1.7.5   2021-10-04 [1] CRAN (R 4.0.2)
    #>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
    #>  styler        1.5.1   2021-07-13 [1] CRAN (R 4.0.2)
    #>  tibble        3.1.5   2021-09-30 [1] CRAN (R 4.0.2)
    #>  tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.0.2)
    #>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.0.2)
    #>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.0.2)
    #>  withr         2.4.2   2021-04-18 [1] CRAN (R 4.0.2)
    #>  xfun          0.25    2021-08-06 [1] CRAN (R 4.0.2)
    #>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
    #> 
    #> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by rich-iannone** [comment]
This should now work as of the recent commit c4066e2b222f0b0967fcd3870b7d5d5fe6f223fc. Apologies for having taken so long to get to a fix for this.

I'm confident that this'll remove the error that occurs from simply loading the package before using `knit_child()`.
