### ISSUE TITLE
typo in soft deprecation warning when using read_fn

### ISSUE THREAD

**Issue by LDalby** [rstudio/pointblank#386]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

The warning issued when using `read_fn` reads:

```r
Warning message:
The `read_fn` argument is undergoing soft deprecation; instead:
 * Use the in the `tbl` argument for in-memory tables.
 * Or supply a function or table-prep formula to `tbl`. 
 ```
There is a _the in_ to much in the first bullet.

Sorry, but I don't have the time right now to open af PR to fix this, so this will have to do (for now at least)

Best
Lars

**Comment by rich-iannone** [comment]
Thanks so much for reporting this. I rewrote the message in c38c2edb87ce919b14753af6b445087607c3a016 .
