### ISSUE TITLE
Install fails due to missing packages

### ISSUE THREAD

**Issue by ekothe** [rstudio/pointblank#4]
Installation required manual installation of rJava, Hmisc, and lazyWeave

**Comment by rich-iannone** [comment]
@ekothe thanks for posting this issue. It's strange that the install didn't capture the dependencies. Did you have to manually determine which additional packages needed installation and then manually install or where these interactive-type installs (where you have to manually download supporting libraries)?

I'll see if I can reproduce this on a separate machine. Also, maybe important, which OS were you using?

**Comment by Lingtax** [comment]
@rich-iannone We just had repeated fails of install_github() , it would name a missing dependency each time but didn't install. 
This is occurring on our workplace desktops running Windows 7.

**Comment by rich-iannone** [comment]
@Lingtax thanks for reporting this. What was the name of the missing dependency?

**Comment by Lingtax** [comment]
As per @ekothe: lazyWeave. But I also was missing digest and had to install manually.

**Comment by rich-iannone** [comment]
@ekothe @Lingtax I've added those packages are requirements should they should automatically install when installing this package. I'm closing this but please re-open if you experience this again.

**Comment by nutterb** [comment]
I'm getting ready to update `pixiedust` soon.  You'll want to require `pixiedust >= 0.8.0` when I do.  0.7.5 has a bug that makes it incompatible with the most recent version of  `dplyr`.  

When I do the release, I'll also drop the dependency on `lazyWeave`.

**Comment by rich-iannone** [comment]
@nutterb Thanks for letting me know. I'll watch for the release, make the dependency changes, and update on CRAN shortly thereafter.

**Comment by rich-iannone** [comment]
@nutterb Thanks for the PR and your time on this. Closing.
