### ISSUE TITLE
pointblank throws error on grouped dataset

### ISSUE THREAD

**Issue by eastclintw00d** [rstudio/pointblank#402]
## Description

I accidently passed a grouped dataset to a pointblank agent and had to spend some time on finding out what caused the error. If throwing an error is intended behaviour in this situation it would be nice to have a self-explaining error message.

## Reproducible example

```
small_table |> 
  group_by(e) |> 
  create_agent() |> 
  col_vals_in_set(vars(a, c), 1:10) |> 
  interrogate()
```

## Session info

Tested on pointblank 0.10.0

**Comment by rich-iannone** [comment]
Sorry for taking awhile to get to this. I think I'll automatically execute `ungroup()` on any grouped table that ingested by functions with a `tbl` argument. I don't believe stopping is necessary or correct. Any datasets 'passed through' a validation function (i.e., no `agent()` or `interrogate()`) should be expected to be the same when returned (ungrouping is internal and shouldn't affect the return value).

**Comment by rich-iannone** [comment]
This is now fixed in https://github.com/rich-iannone/pointblank/commit/dcc5d0d2b41e02424f7affe9767435db14c412a0. Thanks for submitting this issue!
