### ISSUE TITLE
actions_levels and all_passed question

### ISSUE THREAD

**Issue by homer3018** [rstudio/pointblank#418]
## Description

So I'm using pointblank in the context of shiny, and as far as I understand (please correct me if I'm wrong !), `all_passed` is the only way to get the result of an interrogation.
Although I'm setting specific `action_levels` to not trigger any of these, the test is still failing with `col_vals_not_null` since there are some NA values, which is ok up to a point that I thought I could define with the `action_levels`. 

## Reproducible example
This will return FALSE.
```
a <- dplyr::tibble(
    a = c(5, 7, 6, 5, NA, 7)
) %>%
    create_agent(
        label = "A very *simple* example.",
        actions = action_levels(notify_at = 0.9, warn_at = 0.95, stop_at = 0.99)
    ) %>%
col_vals_not_null(vars(a)) %>% 
    interrogate()

all_passed(a)
```
## Expected result

Not sure, but at first I thought that this would pass.

## Question
I have a lot of integer values, not in a specific set, and there can be NAs in there as well. How can I check that I don't have more than 10% for instance, without failing the test, e.g. 9% of NAs would be OK.

Apologies of I missunderstood how this all works. Hopefully someone will be able to shed some light on this :)

**Comment by rich-iannone** [comment]
Sorry for the ambiguity in how `all_passed()` is documented. All passed really means that every test unit in every validation step passed, and this is irrespective of the thresholds set by `action_levels()`. 

However there is a better way to get at the results: use the `get_agent_x_list()` function on the agent `a` in your example (https://rich-iannone.github.io/pointblank/reference/get_agent_x_list.html). After producing the x-list object, take a look at the `f_passed` (fraction passed) element, which is a vector of passing test units over total test units for each validation step. 

Let me know if this helps!

**Comment by homer3018** [comment]
Thanks for the clarification.
The `get_agent_x_list()$f_passed` does provide more granularity, but still not what I was looking for.
My intent was to allow a test to pass by looking at the amount of lines or percent rows that are passing/failing for a particular step. This function gives me the overall pass/fail status for each step but basically will give me a 0 as soon as one single line is not passing a particular step.

That's ok :) I have now understood the thinking behind this and have adjusted my tests.

Maybe food for thoughts for a future release ?
