### ISSUE TITLE
Column value validation fails with ODBC (Postgresql) table backend

### ISSUE THREAD

**Issue by brancengregory** [rstudio/pointblank#429]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/main/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rich-iannone/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

When using an ODBC (Postgres) backend for validations, using the `col_vals_lte` function with a date value errors:
```
ERROR: operator does not exist: date <= numeric;
```
It appears the `value` is being sent to the backend as a number.
This happens regardless of how the `value` is constructed, e.g. `as.Date()`, `as.Posixlt()`, `lubridate::today()` etc.

## Reproducible example

I'm sorry, I don't know how to create a reprex for a database backend. I would love to know how though!

## Expected result

A valid check of whether values in column are of a date less than or equal to today.

**Comment by brancengregory** [comment]
Per usage in this [article](https://dev.solita.fi/2020/12/16/data-quality-with-r.html), I found that things work if you convert the date to a character. This is a great workaround, but it would be nice to be able to pass something like `lubridate::today()` directly.

I might could help implement this with a couple of pointers on where to begin!

**Comment by brancengregory** [comment]
Closing this because it would be fixed  by a database driver like `{odbc}` or `{RPostgres}`, not `{pointblank}`

**Comment by pachadotdev** [comment]
@brancengregory hi! can you try with the development version of RPostgres?

**Comment by brancengregory** [comment]
@pachadotdev  RPostgres handles this case well, on release and development. My comment was misleading, sorry. I only meant that the issue would be in whatever driver was used, and in my case that was odbc, so if there is still an issue it would be there. I haven't checked the status in a couple of months since I've already moved away from odbc this year. I'll definitely report back if I do, though!
