### ISSUE TITLE
Way to create custom labels for `segments`

### ISSUE THREAD

**Issue by Aariq** [rstudio/pointblank#451]
## Prework

- [x] Read and abide by **pointblank**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/main/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rich-iannone/pointblank/issues) (both open and closed).

## Proposal

Currently the segment that the validation step is operating on is only visible in the interrogation table by mousing over the TBL column.  It would be nice to be able to access that information to make it more visible, for example by adding custom labels.  I could imagine using `glue` syntax possibly:

``` r
small_table |> 
  create_agent() |> 
  col_vals_lt(
    c, 8,
    segments = vars(f),
    label = "The `col_vals_lt()` step for group '{.segment}'"
  ) |> 
  interrogate()
```

Just an idea

**Comment by yjunechoe** [comment]
Thanks for the suggestion! In dev, you can now do something like:

```r
remotes::install_github("rstudio/pointblank")
library(pointblank)

agent <- create_agent(small_table) %>%  
  col_vals_lt(
    columns = c(a, c),
    value = 8,
    segments = vars(e, f),
    label = "`{.step}()` step for values in column {.col} within the segment {.seg_col}:{.seg_val}"
  ) %>% 
  interrogate()

cat(agent$validation_set$label, sep = "\n")
#> `col_vals_lt()` step for values in column a within the segment e:TRUE
#> `col_vals_lt()` step for values in column a within the segment e:FALSE
#> `col_vals_lt()` step for values in column a within the segment f:high
#> `col_vals_lt()` step for values in column a within the segment f:low
#> `col_vals_lt()` step for values in column a within the segment f:mid
#> `col_vals_lt()` step for values in column c within the segment e:TRUE
#> `col_vals_lt()` step for values in column c within the segment e:FALSE
#> `col_vals_lt()` step for values in column c within the segment f:high
#> `col_vals_lt()` step for values in column c within the segment f:low
#> `col_vals_lt()` step for values in column c within the segment f:mid
```

**Comment by rich-iannone** [comment]
Thanks for being patient on this @Aariq , and huge thanks to @yjunechoe for making this (and much more) possible!
