### ISSUE TITLE
Validation failed beyond the proportional threshold level

### ISSUE THREAD

**Issue by ramamet** [rstudio/pointblank#466]
## Description

If I run the following function, which parses  proportional failure threshold value:

`expect_col_vals_lt(small_table, columns = vars(c), value = 5, threshold = 0.64) ` 

It's returning, 

"Error: Exceedance of failed test units where values in `c` should have been < `5`.
The `expect_col_vals_lt()` validation failed beyond the proportional threshold level (0.64). 
 failure level (0.61538) >= failure threshold (0.64)" 

Why is 0.64, less than 0.61538 (as I would expect greater than) value?. How can I safely make sure that the failure threshold value works?.

## Reproducible example
expect_col_vals_lt(small_table, columns = vars(c), value = 5, threshold = 0.64) 

## Expected result
The failure conditional value (0.61538) should be less than given proportional failure threshold (0.64). When I have entered the failure threshold (0.654), then the error message is strangely disappeared. Why is proportional failure threshold giving a strange result?

## Session info

> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
[4] LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pointblank_0.11.2

loaded via a namespace (and not attached):
 [1] fansi_1.0.4            withr_2.5.0            utf8_1.2.3             digest_0.6.31         
 [5] dplyr_1.1.0            brio_1.1.3             R6_2.5.1               lifecycle_1.0.3       
 [9] magrittr_2.0.3         pillar_1.8.1           rlang_1.0.6            cli_3.6.0             
[13] rstudioapi_0.14.0-9000 testthat_3.1.6         vctrs_0.5.2            generics_0.1.3        
[17] tools_4.1.0            glue_1.6.2             fastmap_1.1.1          compiler_4.1.0        
[21] pkgconfig_2.0.3        blastula_0.3.3         htmltools_0.5.4        tidyselect_1.2.0      
[25] tibble_3.1.8          

Thank you.

**Comment by michaelbgarcia** [comment]
Hi @ramamet. I started using this package and love it. I came across this issue and wanted to provide my input of what I think is happening. This appears to be a result of the rounding of the expected number of failures after applying a proportion set in the threshold. In your example, `small_table` has 8 failures out of 13 observations which means `8/13 = 61.538%` failure rate. Your threshold of `0.64` means that `0.64 * 13 = 8.32` units must fail to produce an error. The `8.32` rounds down to `8`, hence the error. To test, if you set a threshold of `0.653` and then `0.654` this becomes clearer:
 - `0.653 * 13 = 8.489 = 8.4 = 8` -> FAIL
 - `0.654 * 13 = 8.502 = 8.5 = 9` -> PASS

Looks like fractional amounts are truncated to the 10th decimal place, then rounded.


``` r
library(pointblank)
expect_col_vals_lt(small_table, columns = vars(c), value = 5, threshold = .653)
#> Error: Exceedance of failed test units where values in `c` should have been < `5`.
#> The `expect_col_vals_lt()` validation failed beyond the proportional threshold level (0.653).
#> * failure level (0.61538) >= failure threshold (0.653)
expect_col_vals_lt(small_table, columns = vars(c), value = 5, threshold = .654)
```

<sup>Created on 2023-03-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rich-iannone** [comment]
Thanks @michaelbgarcia for providing the explanation! Will close this issue now.
