### ISSUE TITLE
create_agent error : could not find function "stop_if_not_gt"

### ISSUE THREAD

**Issue by dsolito** [rstudio/pointblank#467]
Hi,
Thank you for this wonderful package!
Since gt 0.9.0 and pointblank 0.11.3 I get an error when `create_agent()` function is called.

Test with your exemple 

`create_agent(
  tbl = ~ small_table,
  tbl_name = "small_table",
  label = "An example.",
  actions = action_levels(
    warn_at = 0.10,
    stop_at = 0.25,
    notify_at = 0.35,
    fns = list(notify = ~ email_blast(
      x,
      to = "joe_public@example.com",
      from = "pb_notif@example.com",
      msg_subject = "Table Validation",
      credentials = blastula::creds_key(
        id = "smtp2go"
      )
    ))
  ), 
  end_fns = list(
    ~ beepr::beep(2),
    ~ Sys.sleep(1)
  ), 
  embed_report = TRUE,
  lang = "fr", 
  locale = "fr_CA"
)`

Error in stop_if_not_gt(data = data) : 
  could not find function "stop_if_not_gt"

I don't see this function in {gt} anymore, is it linked ?

**Comment by dsolito** [comment]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/46330149/229376009-e7674696-4099-4e02-b62d-b78994d9f0c1.png">

**Comment by dsolito** [comment]
Function name has changed.
https://github.com/rstudio/gt/blob/master/R/build_data.R

**Comment by rich-iannone** [comment]
Thank you for catching this relatively fast! It is indeed a bad bug and one I wish I could've avoided. Will fix this and resubmit package to CRAN.

**Comment by dsolito** [comment]
Yeah, was not aware that you are also one of the main contributor of the {gt} package.
Thank you !

**Comment by dsolito** [comment]
Thanks!

**Comment by rich-iannone** [comment]
You're welcome! (And sorry it took so long.)
