### ISSUE TITLE
pointblank site down?

### ISSUE THREAD

**Issue by lucas-nelson-uiuc** [rstudio/pointblank#486]
Wondering if this is consistent with other users - is this expected?

**Comment by rich-iannone** [comment]
The ownership of the repository is being transferred to Posit. Until I regain access to the repository and rebuild the pkgdown site, it will unfortunately be down during that time.

**Comment by rich-iannone** [comment]
It's now back up at https://rstudio.github.io/pointblank/. This is also advertised on the README now. Thanks for your patience on this!

**Comment by lucas-nelson-uiuc** [comment]
thanks big time Rich!
