### ISSUE TITLE
Using for loop

### ISSUE THREAD

**Issue by ZimSci** [rstudio/pointblank#489]
I have a folder with 89 tables/files and I am trying to interrogate those tables in pointblank. Is it possible to use a for loop to create an agent and then interrogate all the files at once? Please advise what the best way would be (if any) so that I dont have to create an agent for all the 89 tables. Thank you.

**Comment by yjunechoe** [comment]
Good question. Firstly, I would read the tables into R and save them as a named list of dataframes. So something like:

```r
tbl_list <- list(
  x = data.frame(a = "A"),
  y = data.frame(a = TRUE),
  z = data.frame(a = 1)
)
```

Then I would write a function that accepts a name from that list to grab the corresponding dataframe and run some set of validations on it:

```r
apply_validations <- function(tbl_name) {
  tbl_list[[tbl_name]] %>% 
    create_agent(tbl_name = tbl_name) %>% 
    col_is_character("a") %>% 
    # Write more validation steps here!
    interrogate()
}
```

Applying this function to each data frame can be a single call to `lapply()`. This produces another list, where each element is the `interrogate()`-ed agent for each data frame.

```r
agent_list <- lapply(names(tbl_list), apply_validations)
agent_reports <- lapply(agent_list, get_agent_report)
```

So then something like `agent_reports[[1]]` will give you the agent report for the first data frame.

Once you have a list of agents, you could go even further and stick them all inside a single html div and render that div, to view all reports at once.

```r
do.call(htmltools::div, agent_reports) %>% 
  print(browse = TRUE)
```

![image](https://github.com/rstudio/pointblank/assets/52832839/029c9815-dc32-4650-ac38-a5ebd47704de)
