### ISSUE TITLE
Support `where()` predicates for tidyselect in `info_columns()`

### ISSUE THREAD

**Issue by yjunechoe** [rstudio/pointblank#502]
## Prework

- [x] Read and abide by **pointblank**'s [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/pointblank/blob/main/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rstudio/pointblank/issues) (both open and closed).

## Problem

Currently, `columns` in `info_columns()` does have the new/complete tidyselect backend, but cannot utilize the `where()` helper:

```r
informant <- create_informant(small_table)
# Works
informant %>% 
  info_columns(starts_with("date"), info = "Data about a time point")
# Should do the same thing but doesn't work
informant %>% 
  info_columns(where(lubridate::is.timepoint), info = "Data about a time point")
#> Warning message:
#> No columns were matched with the expression used, so, no info was added. 
```

This is because columns are resolved against this dummy data that's re-generated from the column names:

https://github.com/rstudio/pointblank/blob/70c2075b4d7ba0434a4e27a159d52cfa051ebdd7/R/info_add.R#L450-L455

Where the `x` looks like the following:

```r
#> # A tibble: 1 × 8
#>   date_time  date     a     b     c     d     e     f
#>       <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1         1     1     1     1     1     1     1     1
```

## Proposal

I have two ideas:

1) Only resolve against the dummy data if the data is read directly (i.e., `informant$tbl` is not NULL). This is super simple - we can just `if`-case the above lines from `info_columns()`. (Now in #503)

This is good, but not perfect - it means that the support for `where()` is not extended to databases and even simple cases like:

```r
create_informant(~small_table)$tbl
#> NULL
```

2) Have the informant store information about **column prototypes**, to at least support `is.<class>` predicates in `where()`. (Now in #504 )

I think this could be a good middle ground that doesn't break the laziness/lightweight-ness of informants. Essentially, the proposal is to add an extra bit of information to the informant which is just the dataframe *header*, like:

```r
head(small_table, 0)
#> # A tibble: 0 × 8
#> # ℹ 8 variables: date_time <dttm>, date <date>, a <int>, b <chr>, c <dbl>, d <dbl>, e <lgl>, f <chr>
```

We don't have to execute an extra query for this. We can do it all in one go here, at the informant's creation:

https://github.com/rstudio/pointblank/blob/70c2075b4d7ba0434a4e27a159d52cfa051ebdd7/R/utils.R#L746-L763

The proposal is for this function to also return information about the prototypes (`col_ptypes`). So something like:

```r
get_r_column_names_types <- function(tbl) {
  
  suppressWarnings(
    column_header <-
      tbl %>%
      utils::head(1) %>%
      dplyr::collect()
  )
  column_names_types <-
    vapply(column_header, function(x) class(x)[1], character(1))
  
  list(
    col_names = names(column_names_types),
    r_col_types = unname(unlist(column_names_types)),
    col_ptypes = utils::head(column_header, 0)
  )
}
```

Then we can string this 0-row `col_ptypes` dummy data along for tidyselect purposes. The one tricky part is that this info needs to be invisible to gt-rendering/yaml-writing, but I think this could also serve as an opportunity to build in a `$_private`-like property to the informant for future extensibility.

It's overall a small surgery but does touch multiple behaviors, so I'd like to hear your thoughts first. The hope is to get something like below working. LMK what you think!

```r
create_informant(~ small_table) %>% 
  info_columns(
    columns = where(lubridate::is.timepoint),
    info = "Data about a time point"
  )
```
![image](https://github.com/rstudio/pointblank/assets/52832839/cd066602-d91c-41a5-b265-80d554be35ca)

**Comment by rich-iannone** [comment]
I think having Option 2 working would be the best! That final example makes this all really compelling.

**Comment by yjunechoe** [comment]
Sounds good! Will explore option 2 in a second PR.
