### ISSUE TITLE
Have some of the step functions use columns (not just numbers) as comparisons

### ISSUE THREAD

**Issue by shawnagill** [rstudio/pointblank#51]
Love this package! I'm setting up all sorts of validations and one thing I think would be useful is to enable a direct comparison of one column to another.

For example if we wanted to validate that column a is always greater than column b, we should be able to use `col_vals_gt(vars(a), vars(b))`. What do you think?

Again, this package is incredible. Thanks!

**Comment by rich-iannone** [comment]
Thanks for submitting this issue. Yes! I think this would be a great idea and one of the next things to get added. This will be added alongside support to compare date and time values.
