### ISSUE TITLE
`col_vals_equal()` doesn't match two `NA` values

### ISSUE THREAD

**Issue by vhh711** [rstudio/pointblank#513]
## Prework

* [ X] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/pointblank/blob/main/.github/CONTRIBUTING.md).
* [ X] If there is [already a relevant issue](https://github.com/rstudio/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question

I'm not sure if my issue is tied to issue #15, but the validation function I have a question about is mentioned there. 

I'm validating that two columns contain equal values. Both columns have NA observations and numeric observations. I'm encountering that observations where both columns have an NA fail the validation step. When I enable the `na_pass = TRUE` argument, the rows no longer fail the validation step. I was concerned this might pass through rows where one column's observation is a numeric value and the comparison column has an NA. So, I ran a simple test, and indeed the `na_pass = TRUE` argument passes rows where one observation is a number and the other is an NA. 

Am I misunderstanding how the function interprets or treats NAs in relation to numeric values?
Is this the intended behavior of the function?
Would utilizing the preconditions argument address this issue? Could I simply mutate the NA values to equal some number which would then give me an accurate pass/fail?
Or is this a bug?

## Reproducible example

* [ X] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ X] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ X] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ X] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

**No `na_pass `argument**
```
df <- data.frame(
  a = c(2, 3, NA, 4, 5, NA),
  b = c(2, 4, NA, 4, 5, 1)
)

al = action_levels(warn_at = 1) 

agent <- create_agent(
  tbl = df,
  tbl_name = "Are column values equal",
  actions = al
  ) %>% 
  col_vals_equal(
    columns = a,
    value = vars(b),
    label = "Do values match?"
  ) %>% interrogate()

agent
```
![image](https://github.com/rstudio/pointblank/assets/88150730/39ff6991-c0f0-43ab-9000-05ec500ac380)

As you can see in the above screenshot, 3 rows fail. However, I expected two rows to fail. Is this the expected behavior for `col_vals_equal()`?

**Using `na_pass `argument**
```
df <- data.frame(
  a = c(2, 3, NA, 4, 5, NA),
  b = c(2, 4, NA, 4, 5, 1)
)

al = action_levels(warn_at = 1) 

agent <- create_agent(
  tbl = df,
  tbl_name = "Are column values equal",
  actions = al
  ) %>% 
  col_vals_equal(
    columns = a,
    value = vars(b),
    label = "Do values match?",
    na_pass = TRUE
  ) %>% interrogate()

agent
```
![image](https://github.com/rstudio/pointblank/assets/88150730/6a889a9d-aa96-4d9c-a837-42c44068cf83)

As you can see in the above screenshot only 1 row fails, but I expected two to fail.

_Originally posted by @vhh711 in https://github.com/rstudio/pointblank/issues/15#issuecomment-1854829095_

**Comment by yjunechoe** [comment]
I think that's consistent with the expectation for `col_vals_equal()` to use `==` for checking equality - the following is not `TRUE`:

``` r
NA == NA
#> [1] NA
```

With regards to `na_pass`, that's a general argument for whether `NA` _results_ from the validation operations should count as a pass. As far as `col_vals_equal()` is concerned, `NA == NA` and `NA == 1` are both `NA` - the `na_pass` argument is not aware of how you got to the `NA` value with `==`. So the fact that both rows involving `NA` values pass in your second example with `na_pass = TRUE` is again the intended/documented behavior.

For a workaround, you can either recode the `NA`s into some value that's legible to `==` in the `preconditions` argument, as you mention, or use `col_vals_expr()` instead and be more explicit about the looser criteria for equality. That latter approach can get a bit more verbose, but either of the following lets you match two `NA`s as a match but an NA with some other value as a mismatch:

```r
col_vals_expr(
  expr = expr(Vectorize(identical)(a, b))
)
```

```r
col_vals_expr(
  expr = expr(!xor(is.na(a), is.na(b)) & a == b)
)
```

**Comment by vhh711** [comment]
Thanks so much for this explanation! I appreciate it.

I'll give the `preconditions `argument and the `col_vals_expr()` options  a try.

**Comment by rich-iannone** [comment]
@yjunechoe thank you for the explanation :) and I think we can close this one.
