### ISSUE TITLE
`quarto render --to html` makes some html tags visible in the validation report

### ISSUE THREAD

**Issue by cregouby** [rstudio/pointblank#518]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/pointblank/blob/main/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

From a  basic agent , the pointblank report in a quarto html document includes unexpected html tags "<div arial label=" and "<span style=" within the cells : 
![image](https://github.com/rstudio/pointblank/assets/10136115/6c09d217-9ae6-48ec-a661-c5ddff599558)

This appends equally from the Rstudio IDE "Render" button and from the cli "> quarto render reprex.qmd --to html"

The rendering of the same content in a Rmd document do not have the issue.

## Reproducible example
```qmd
---
title: "Untitled"
format: html
---

```{r}
library(pointblank)
library(tibble)
create_agent(
  tibble(iris),
  label = "Iris Dataset") |> 
  col_exists(columns = c("Sepal.Length", "Sepal.Width", "Species")) |> 
  interrogate()
```
<sup>Created on 2024-02-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

## Expected result
The expected result can be obtained from knitr on the Rmd file equivalent
![image](https://github.com/rstudio/pointblank/assets/10136115/c5a8b5f3-a1e4-44ee-8a18-337bda6f658a)

## Session info
<sup>Created on 2024-02-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` shell
$ quarto --version
1.5.16
```

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.2 (2023-10-31)
#>  os       Ubuntu 22.04.4 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language fr_FR
#>  collate  fr_FR.UTF-8
#>  ctype    fr_FR.UTF-8
#>  tz       Europe/Paris
#>  date     2024-02-28
#>  pandoc   3.1.1 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version     date (UTC) lib source
#>  blastula      0.3.5       2024-02-24 [3] RSPM (R 4.3.0)
#>  cli           3.6.2       2023-12-11 [1] CRAN (R 4.3.2)
#>  commonmark    1.9.0       2023-03-17 [1] CRAN (R 4.3.0)
#>  digest        0.6.33      2023-07-07 [1] CRAN (R 4.3.1)
#>  dplyr         1.1.4       2023-11-17 [1] CRAN (R 4.3.2)
#>  evaluate      0.23        2023-11-01 [1] CRAN (R 4.3.2)
#>  fansi         1.0.6       2023-12-08 [1] CRAN (R 4.3.2)
#>  fastmap       1.1.1       2023-02-24 [1] CRAN (R 4.3.0)
#>  fs            1.6.3       2023-07-20 [1] CRAN (R 4.3.1)
#>  generics      0.1.3       2022-07-05 [1] CRAN (R 4.3.0)
#>  glue          1.6.2       2022-02-24 [1] CRAN (R 4.3.0)
#>  gt            0.10.1      2024-01-17 [3] RSPM (R 4.3.0)
#>  htmltools     0.5.7       2023-11-03 [1] CRAN (R 4.3.2)
#>  knitr         1.45        2023-10-30 [1] CRAN (R 4.3.2)
#>  lifecycle     1.0.4       2023-11-07 [1] CRAN (R 4.3.2)
#>  magrittr      2.0.3       2022-03-30 [1] CRAN (R 4.3.0)
#>  markdown      1.12        2023-12-06 [1] CRAN (R 4.3.2)
#>  pillar        1.9.0       2023-03-22 [1] CRAN (R 4.3.0)
#>  pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 4.3.0)
#>  pointblank  * 0.11.4.9000 2024-02-27 [1] Github (rstudio/pointblank@28ca29e)
#>  purrr         1.0.2       2023-08-10 [1] CRAN (R 4.3.1)
#>  R.cache       0.16.0      2022-07-21 [1] CRAN (R 4.3.1)
#>  R.methodsS3   1.8.2       2022-06-13 [1] CRAN (R 4.3.1)
#>  R.oo          1.25.0      2022-06-12 [1] CRAN (R 4.3.1)
#>  R.utils       2.12.3      2023-11-18 [1] CRAN (R 4.3.2)
#>  R6            2.5.1       2021-08-19 [1] CRAN (R 4.3.0)
#>  reprex        2.1.0       2024-01-11 [3] RSPM (R 4.3.0)
#>  rlang         1.1.2       2023-11-04 [1] CRAN (R 4.3.2)
#>  rmarkdown     2.25        2023-09-18 [1] CRAN (R 4.3.1)
#>  rstudioapi    0.15.0      2023-07-07 [1] CRAN (R 4.3.1)
#>  sass          0.4.8       2023-12-06 [1] CRAN (R 4.3.2)
#>  sessioninfo   1.2.2       2021-12-06 [1] CRAN (R 4.3.0)
#>  styler        1.10.2      2023-08-29 [1] CRAN (R 4.3.1)
#>  tibble      * 3.2.1       2023-03-20 [1] CRAN (R 4.3.0)
#>  tidyselect    1.2.0       2022-10-10 [1] CRAN (R 4.3.0)
#>  utf8          1.2.4       2023-10-22 [1] CRAN (R 4.3.2)
#>  vctrs         0.6.5       2023-12-01 [1] CRAN (R 4.3.2)
#>  withr         2.5.2       2023-10-30 [1] CRAN (R 4.3.2)
#>  xfun          0.41        2023-11-01 [1] CRAN (R 4.3.2)
#>  xml2          1.3.6       2023-12-04 [1] CRAN (R 4.3.2)
#>  yaml          2.3.8       2023-12-11 [1] CRAN (R 4.3.2)
#> 
#>  [1] /home/creg/R/x86_64-pc-linux-gnu-library/4.3
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by yjunechoe** [comment]
This looks like the same issue as https://github.com/rstudio/gt/issues/1488 (and other issues linked within)

Applying a workaround from https://github.com/quarto-dev/quarto-cli/discussions/7493, the reprex renders fine on quarto:

```r
library(pointblank)
create_agent(iris) |> 
  col_exists(Sepal.Length) |>
  interrogate() |>
  get_agent_report() |>
  gt::fmt(fns = identity) # `gt::fmt_passthrough(escape = FALSE)` also works here
```

![image](https://github.com/rstudio/pointblank/assets/52832839/c86dca8e-7814-4f75-8534-aa122fc802ea)

@rich-iannone Should we apply some sort of a workaround like the above before rendering agent/informant reports, to suppress generation of the `data-qmd` attribute? Or would you prefer to just fix it upstream in `{gt}`?

---

On a separate but related note, it looks like `<code>` inside the report is inheriting the purple color from quarto's theme. I think we should hard code `color: black;` in the agent's css - here and possibly elsewhere?

https://github.com/rstudio/pointblank/blob/28ca29e544145021ba0fa543a38e7fe40edecaab/R/get_agent_report.R#L1952-L1956

**Comment by rich-iannone** [comment]
@yjunechoe I was just exploring this this morning! A bit more work is required upstream in gt to fix https://github.com/rstudio/gt/issues/1488. However, I think we should sidestep that for now and use `gt::fmt(fns = identity)` wherever needed. Also agree with the replacement of purple `code` text with black.

Would you be able to handle this? I swear this'll be the last thing before the release :/

**Comment by yjunechoe** [comment]
No worries! I'd like to see this fixed for this release as well. I'll make a PR!
