### ISSUE TITLE
Column names with spaces causes incorrect validation error

### ISSUE THREAD

**Issue by JamesHWade** [rstudio/pointblank#530]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/pointblank/blob/main/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

When using `col_val_lt()`, I get an error if there is a space in the column name. This also occurs with `col_val_gt()`. 

## Reproducible example

I removed the HTML from the reprex.

``` r
library(pointblank)
mtcars |> 
  dplyr::rename(`disp units` = disp) |>
  create_agent() |> 
  col_vals_lt(`disp units`, 1000) |> 
  interrogate()
```

<sup>Created on 2024-03-14 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Expected result

The validation should proceed instead of result in an error.

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.

**Comment by yjunechoe** [comment]
Thanks for the report! I can reproduce this - it's a bug in the `tbl_val_comparison()` function that powers `col_vals_lt()`.
