### ISSUE TITLE
Provide a static PNG logo

### ISSUE THREAD

**Issue by hadley** [rstudio/pointblank#548]
It'd be super useful to have a static version of the pointblank logo to include in presentations etc. I always end up taking a screenshot of the website, which is not ideal.

**Comment by hadley** [comment]
FWIW it would be useful to make the (outside-the-hex) background transparent, so it's a little easier to use everywhere.

**Comment by rich-iannone** [comment]
> FWIW it would be useful to make the (outside-the-hex) background transparent, so it's a little easier to use everywhere.

Now available here: 
https://github.com/rstudio/pointblank/blob/main/man/figures/logo_static.png
