### ISSUE TITLE
Could create_multiagent accept a list of agents?

### ISSUE THREAD

**Issue by florianm** [rstudio/pointblank#552]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/pointblank/blob/main/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/pointblank/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question

What would you like to know?
How can I create a multiagent from a list of agents, e.g. a column of a tibble containing agents?

My use case is to generate one combined pointblank report for an arbitrary number of CSV files. I generate a tibble with one row for each file to validate, annotate the tibble with a column containing an interrogated agent for each file, and then would like to render a multiagent report into one single Rmd.

`create_multiagent` accepts a series of agent objects but doesn't accept a list of agents. 

I've described my approaches at [the posit forum](https://forum.posit.co/t/how-to-turn-a-list-into-a-as-function-parameter/189750/3).

```
# Tibble "csv_info" has a column "agent" containing interrogated agents.

ma <- pointblank::create_multiagent(
  csv_info$agent[[1]], 
  csv_info$agent[[2]], 
  csv_info$agent[[3]]
) # this works but doesn't scale

pointblank::create_multiagent(csv_info$agent) # Fails because csv_info$agent already is a list
```

## Reproducible example

* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

Should I convert my list of agents into something equivalent to dynamic dots?
```
my_list <- list(1,2,3)

# A function that takes dynamic dots and turns them into a list
the_function <- function(...){
 internal_list <- list(...)
 internal_list
}

# Somehow prepare my_list to be used as function argument
my_list_as_dots <- UNKNOWN_FUNCTION(my_list)

the_function(my_list_as_dots) == my_list
```

Or is there some functional approach to feed the list of agents to create_multiagent?

Or could create_multiagent be modified to accept a list of agents? (I assume even if this were a good idea compatibility might be an issue.)
Something like this:
```
create_multiagent <- function(
    ...,
    lang = NULL,
    locale = NULL,
    agent_list=NULL
) {

if (is.null(agent_list)) agent_list=list(...)
```

**Comment by florianm** [comment]
Answer fresh from the posit forum: A patch that makes `!!!` work.

```
create_multiagent2 <- function(...) {
  do.call("create_multiagent", list2(...))
}

create_multiagent2(!!!agent_list) |>
  pointblank::get_multiagent_report(display_mode = "long")
```

So my follow-up question is:
Is feeding a list of agents into create_multiagent an expected or supported workflow? If so, would it make sense to describe the above somewhere in the docs?

**Comment by yjunechoe** [comment]
It's a feature of `do.call()` that you can pass a single `list()` in place of `...`. So even without the `list2()` patch you could do:

```r
agent_list <- list(my_agent1, my_agent2, my_agent3)
do.call(create_multiagent, agent_list) # vs. create_multiagent(my_agent1, my_agent2, my_agent3)
```

That said, `!!!` is indeed more convenient and I suspect it's also more familiar to most users. This is definitely doable!

@rich-iannone I see just a few cases of `list(...)` in user-facing functions. 

- `create_multiagent()`
- `col_schema()`
- `info_tabular()`, `info_columns()`, `info_section()`
- `stop_if_not()`

Should we just make a global switch to `list2()` for collecting user-supplied dots? I don't see any immediate issues with this.

**Comment by florianm** [comment]
@yjunechoe Wow - that's even better, thanks so much! I can absolutely live with `do.call(create_multiagent, agent_list)` as it requires no extra function.
Still, would love to see those few functions accepting lists as well!

**Comment by yjunechoe** [comment]
Great! BTW, just for completeness, I should mention that you can *also* use the splice operator `!!!` without depending on `list2()`:

```r
rlang::inject(
  create_multiagent2(!!!agent_list)
)
```

**Comment by florianm** [comment]
Oh I was missing the `inject` - thanks!
