### ISSUE TITLE
Regression in `get_agent_report(arrange_by = "severity")`

### ISSUE THREAD

**Issue by yjunechoe** [rstudio/pointblank#572]
I introduced this bug when addressing https://github.com/rstudio/pointblank/pull/565, where I failed to account for cases when row order may shift due to `arrange_by`.

```r
library(pointblank)
x <- iris |> 
  create_agent(actions = action_levels(warn_at = 1)) |> 
  col_exists("Petal.Length",
             active = has_columns(iris, Petal.Length)) |> 
  col_exists("Spec",
             active = has_columns(iris, Spec)) |> 
  col_exists("noexist") |> 
  interrogate()

get_agent_report(x, arrange_by = "severity")
```

CRAN:

![image](https://github.com/user-attachments/assets/a2db645c-df4e-4f3c-8479-b0349fe79207)

DEV (only some columns are arranged):

![image](https://github.com/user-attachments/assets/e4e7251b-92a5-4ed3-bf42-cc5a3f91aa6c)

Will fix and write tests for ASAP!

**Comment by rich-iannone** [comment]
Thanks for identifying this and putting in the fix! Closing now as https://github.com/rstudio/pointblank/pull/573 is merged.
