### ISSUE TITLE
Reporting across interrogations

### ISSUE THREAD

**Issue by scotbader8858** [rstudio/pointblank#59]
I've been using this package (along with your gt package!) for about a month and it's really helped out a lot at work. We're trying to get our data quality under control and this package solves that problem perfectly (it's actually amazing how everything just seems to work without problems).

A feature request that I have is making a sort of combined report of interrogations for the same table but at different times. We want to have these to see (in a simple table) where things have improved or gotten worse.

I honestly wouldn't be surprised if you weren't thinking about this already, so, if this is something you were planning it would be a great next step.

Thank you so much for all your great packages. You're making my life easier!

**Comment by rich-iannone** [comment]
Thanks for the feature request, it’s a really great idea! I’m going to some work done on it alongside general improvements to reporting.
