### ISSUE TITLE
Enable other database types using odbc?

### ISSUE THREAD

**Issue by happyshows** [rstudio/pointblank#8]
Hi,

It would be very useful if this package and be applied to other DB types too using odbc, which translate into DB specific queries. Any thoughts?

**Comment by rich-iannone** [comment]
That would be great actually. Some of the code uses older dplyr functions like `src_postgres()` and `src_mysql()`, so, I'd like to generalize the DB access with odbc/DBI. 

If you have any specific ideas on this topic, let me know.

**Comment by rich-iannone** [comment]
@happyshows I’ve made improvements in the direction of removing both `dplyr::src_...()` calls and using DBI to create the remote DB connections (this removed issues like auto-disconnects). I’m considering adding new DB types but need to experiment with the **odbc** package before implementing separately or generalizing with of **odbc**.

**Comment by rich-iannone** [comment]
Now in `master`, we can use `tbl_dbi` objects and it seems to be working as well in validations as the `tbl_df` objects. Certainly more tests would be helpful to make sure that this all works as intended, however, these changes go in the direction of using more database types.
