### ISSUE TITLE
More languages to add to make it more usable for more people

### ISSUE THREAD

**Issue by bronsonpetersa** [rstudio/pointblank#80]
Aside from the 5 languages you have now, would you consider adding a few more? Some that I think would be good are Portuguese, Dutch, Danish, Czech, and Polish. Thank you.

**Comment by rich-iannone** [comment]
This is certainly a good idea. The problem is that I don't have much of a grasp of these languages, so I'll have to lean on others to get this translation work done. Even so, the initiative is very much worth the effort.

Thanks so much for this feature request!

**Comment by rich-iannone** [comment]
This is now more actively being worked on (and Portuguese was recently added). We’ll be opening new issues for each target language as we get to work on them. Because of that, this issue will be closed.
