### ISSUE TITLE
A question about the `scan_data()` function

### ISSUE THREAD

**Issue by jenniferp96** [rstudio/pointblank#82]
I tried out the new function `scan_data()` on some of my data tables at work. It's really great as it is and actually has so much more potential. Just wondering if the HTML can be included in a Connect-based Rmarkdown report?

It would be killer to share daily summaries of changing datasets with Connect in this way. By the way, we are using the validation stuff in this package to great effect. Everyone's pretty impressed with the results from this package and I'm teaching people how to use it (our data changes quite a bit and there are constant data quality issues -- pointblank helps us A LOT in this regard and its honestly a lifesaver)

**Comment by rich-iannone** [comment]
Well, I have some good news for you: it totally works! You can use `scan_data()` in an RMarkdown chunk (use `echo=FALSE`) and it’ll appear in the rendered doc. 

There’s also an also an option to disable the top nav bar of the generated HTML from `scan_data()`. So, you can include as many of the report’s sections you want (that’s also an option) and put in other content wherever necessary for the reporting. 

And, with Connect, you can have a multiple of these reporting documents (with historical reports easily accessible in the same place). Try it out and let me know how it goes. Really glad to hear that you and the team like the package. Always feel free to make more feature requests!
