### ISSUE TITLE
suggestion for col_schema improvements

### ISSUE THREAD

**Issue by michaelandersona** [rstudio/pointblank#85]
Rich, first of all this is an incredible package.... we are heavily invested in using it in production. We are now, on a daily basis, checking the data quality of about 80 DB tables and this package (a complete system really) provides everything we need to ensure we are on top of issues. We definitely wouldn't have caught so many problems without this package, it's now indispensable. Anyway enough gushing just know that we are appreciative.

This brings me to my feature request idea.. with the newest cran release of pointblank there is now the ability to validate table schemas. We definitely needed this and there are plans to revise our pointblank scripts to include this. One possibility to make this better is to include some more options in col_schema (the function that is used to define the schema). One option could be to either enforce a strict ordering of columns as defined, or, make the order not essential (like %in%). One more option would be to have the columns specified not necessarily the entire set of columns in the table (an 'at least' idea). I know that would make the schema definition less strict but this is useful in some cases and could be exposed as useful options.

**Comment by rich-iannone** [comment]
Thanks for making use of the package! These are great ideas for the `col_schema_match()`/`col_schema()` combination. I'm planning on making a second round on this (adding features and not disrupting its current defaults). These suggestions will definitely be worked in.
