### ISSUE TITLE
Consider less stringent R version dependence.

### ISSUE THREAD

**Issue by shabbybanks** [rstudio/pointblank#9]
The dependence on R version `>= 3.4.0` means I cannot install this package at work. (We are stuck on R 3.2, and it's not going to change.) I have looked at the dependencies of `pointblank`, and none of them seem to require 3.4, although perhaps some of _their_ dependencies do. I might suggest modifying the `.travis.yml` file to try builds on older releases as a test, _c.f._ [R versions](https://docs.travis-ci.com/user/languages/r/#R-Versions).

**Comment by rich-iannone** [comment]
Thanks for raising this as an issue. I just reduced the R dependency in another package down to R >= 3.2.0 and I'll try to do the same here. I'll certainly perform checking against older releases via Travis, as well.

**Comment by shabbybanks** [comment]
thanks. I sometimes find that `trimws` is the sticky wicket for pre-3.2 builds, requiring the `backports` package, though YMMV. Thanks again for the package, I look forward to testing it.

**Comment by rich-iannone** [comment]
@shabbybanks thanks for the tip on `trimws()`, I removed all uses of that function and replaced with `stringr::str_trim()`. I reduced the R version number based on this function (found on SO, modified slightly here):

```r
min_r_version <- function(pkg) {
  requireNamespace("tools")
  requireNamespace("utils")
  repo <- "https://cloud.r-project.org"
  avail <- utils::available.packages(utils::contrib.url(repo))
  deps <- tools::package_dependencies(pkg, db = avail, recursive = TRUE)
  pkgs <- deps[[1]]
  
  matches <- avail[ , "Package"] %in% pkgs
  pkg_list <- avail[matches, "Depends"]
  vers <- grep("^R$|^R \\(.*\\)$", pkg_list, value = TRUE)
  vers <- gsub("[^0-9.]", "", vers)
  if (length(vers) == 0)
    return("Not specified")
  
  max_ver = vers[1]
  if (length(vers) == 1)
    return(max_ver)
  
  for (v in 2:length(vers))
    if (utils::compareVersion(vers[v], max_ver) > 0)
      max_ver <- vers[v]
  
  max_ver
}
```

When I use it, I find that the **pixiedust** package has a min R requirement of 3.2.1. I dropped this package's requirement down to that for now (in the dev version).

@nutterb could **pixiedust**'s min R version be reduced to 3.2?

**Comment by nutterb** [comment]
I use `trimws` a lot, which was introduced in 3.2.0. I'd prefer not to change it (because I'm an opinionated curmudgeon), so that limits me to no lower than 3.2.0. if someone makes a good case for it, I can go lower.

I just changed my master and dev branches to 3.2.0

**Comment by rich-iannone** [comment]
@nutterb That's great, thanks for changing! Definitely don't mean to suggest switching out `trimws` for anything else (just forgot when it was introduced in R).

**Comment by rich-iannone** [comment]
@nutterb forgot to ask this but are you able to push a patch release of **pixiedust** with the lowered R requirement? Then, I could do the same just after that with **pointblank** and we could all service 3.2 R users.

**Comment by nutterb** [comment]
it will probably be next week before I get it prepped, but I'll let you
know when it is submitted.

**Comment by rich-iannone** [comment]
Thanks! Really appreciate that.

**Comment by shabbybanks** [comment]
@nutterb : I believe you can use `trimws` from the `backports` package, and thus roll the R version dependency back to 3.0. I'll fork and submit a PR. (I don't have a travis account to test, however.)

**Comment by nutterb** [comment]
`backports` doesn't export `trimws`, which causes the checks to fail.  If I were to go back further than 3.2.0, I would prefer to copy the code of `base::trimws` into my source code and just not export it.

**Comment by nutterb** [comment]
Just submitted `pixiedust` 0.8.1.  Should hear back later today.  My dependency is down to R 3.1.2, which is the version `dplyr` depends on.

**Comment by rich-iannone** [comment]
cc: @shabbybanks @nutterb 

Belated thanks for making this possible. The min R version is now 3.1.2. Also removed Java dependencies in the package.

**Comment by shabbybanks** [comment]
Great! Thank you so much, will install and play!
