### ISSUE TITLE
`scan_data` function documentation

### ISSUE THREAD

**Issue by kylelundstedt** [rstudio/pointblank#91]
Hi @rich-iannone,

Loving the new developments in the `pointblank` package.  Just FYI, the `scan_data` [function documentation](https://rich-iannone.github.io/pointblank/reference/scan_data.html) currently states that the "tbl" argument "can be a data frame, a tibble, or a tbl_dbi object".  However, the [function code](https://github.com/rich-iannone/pointblank/blob/aa30c3252cf7431b561a48ca6c5f1109a887f76c/R/scan_data.R#L57) specifically precludes tbl_dbi's as inputs.

The function is truly awesome, so I'm hoping that applying it to tbl_dbi's is a work-in-progress.  :) Regardless, I just wanted to give you the heads up.  Thanks for all the hard work.

Best
Kyle

**Comment by rich-iannone** [comment]
Eep! You’re right. Currently can’t do `tbl_dbi()` with `scan_data()` right now but I do plan to support DB tables soon in that function. In the meantime, I will correct the documentation. Thanks for letting me know!
