### ISSUE TITLE
download option for rows that do not pass validations?

### ISSUE THREAD

**Issue by daranzolin** [rstudio/pointblank#95]
I'm in the process of validating several large datasets. I demo'd pointblank to great interest, but someone asked if I could include the option to download a csv of the rows that fail certain conditions. I then tried to rig up some chunks like:

```
{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pointblank)
library(downloadthis)
```

``` 
{r validate = TRUE}
test1 <- try(col_vals_gt(iris, vars(Sepal.Length), 6), silent = TRUE)
if (inherits(test1, "try-error")) {
  download_this(
    subset(iris, Sepal.Length < 6),
    output_name = "test1 failed rows",
    output_extension = ".csv",
    button_label = "Download data",
    button_type = "warning",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
}

```
But this fails with error:
`Error in if (!error_vec[i]) { : missing value where TRUE/FALSE needed``

The chunks run if I remove the `validate = TRUE` chunk option, but I want to preserve that magic. Is there a way I can get the best of both worlds? Perform validations and include download options?

**Comment by rich-iannone** [comment]
This seems like a great feature that would make a lot of sense in the R Markdown workflow! I'll have to put some work into getting this implemented.

There are some other ideas around getting the fail/pass rows outside of this exact workflow (if you just need to get the work done now), and that's using the `get_sundered_data()` function: https://rich-iannone.github.io/pointblank/reference/get_sundered_data.html. 

BTW, thanks for letting me know about {downloadthis}!
