### ISSUE TITLE
Example not working (?)

### ISSUE THREAD

**Issue by jruizcabrejos** [rstudio/pointblank#98]
Hi! I a friend recommended me the package and I wanted to try it out. However, after trying this example

![Example](https://user-images.githubusercontent.com/25235690/82119709-5c48c800-9746-11ea-9870-89318d2c078a.png)

I had some issues rendering the .html document, with this result:

![Result](https://user-images.githubusercontent.com/25235690/82119739-91551a80-9746-11ea-90ae-7f0ab78bf8ec.png)

Any idea why it might be happening? I also had some troubles running the next example because of the function 'stop_if_not'.

Thanks!

**Comment by rich-iannone** [comment]
Right now, this functionality is only available in the development version of the package. You can try it out using `install_github("rich-iannone/pointblank")`. 

I’m hoping to get this package updated on CRAN in the upcoming week.
